// Regenerates src/templates.generated.ts from templates/*.jinja. The templates are
// imported as text so `bun build --compile` embeds them in the binaries; a directory
// read at runtime would find nothing inside a compiled image.
import { Glob } from "bun";

const root = new URL("..", import.meta.url).pathname;
const names = [...new Glob("*.jinja").scanSync(`${root}templates`)].sort();
const lines = [
  "// Generated by scripts/generate.ts from templates/*.jinja. Do not edit by hand.",
  '/// <reference path="./jinja.d.ts" />',
  ...names.map((n, i) => `import t${i} from "../templates/${n}" with { type: "text" };`),
  "",
  "export const TEMPLATES: Readonly<Record<string, string>> = {",
  ...names.map((n, i) => `  "${n}": t${i},`),
  "};",
  "",
];
await Bun.write(`${root}src/templates.generated.ts`, lines.join("\n"));
process.stdout.write(`${names.length} templates\n`);
