// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/agent_access.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

/**
 * Agent access: the consent page where a person connects an agent (user codes), and the
 * MCP and agent REST calls the agent then makes (developer codes: the agent reads them).
 */
export const agent_access = {
  "agent_access.request_expired": {
    action: "none",
    detail: "This authorisation request has expired. Start again from your agent.",
    description:
      "The consent page was opened for an authorisation request that expired or was used.",
  },
  "agent_access.risk_not_accepted": {
    action: "fix_input",
    detail: "The data risk notice must be accepted",
    description: "Consent was sent without ticking the data risk notice.",
  },
  "agent_access.expiry_unsupported": {
    action: "fix_input",
    detail: "Unsupported expiry",
    description: "Consent named an expiry that is not one of the offered choices.",
  },
  "agent_access.no_enabled_organisation": {
    action: "contact_admin",
    detail: "Pick at least one organisation where agent access is switched on",
    params: ["admin_name", "admin_email"],
    description: "Consent named no organisation that has agent access switched on.",
  },
  "agent_access.grant_not_found": {
    action: "none",
    detail: "Grant not found",
    description: "The agent grant does not exist or is not the caller's to manage.",
  },
  "agent_access.scope_missing": {
    action: "none",
    detail: "This grant does not include the '{scope}' scope",
    audience: "developer",
    description: "An agent called a write tool with a grant that only allows reading.",
  },
  "agent_access.organisation_not_granted": {
    action: "none",
    detail: "Not found",
    audience: "developer",
    description:
      "The organisation is not in the agent's grant; reported missing so ids cannot be probed.",
  },
  "agent_access.disabled_by_admin": {
    action: "contact_admin",
    detail: "An organisation admin has switched off agent access for this organisation",
    audience: "developer",
    description: "The organisation's admins switched agent access off after the grant was made.",
  },
  "agent_access.free_tier_calls_used": {
    action: "upgrade",
    detail:
      "This organisation is on the free tier and has used its {limit} agent calls for this month",
    audience: "developer",
    description: "A free organisation used up its monthly agent call budget.",
  },
  "agent_access.grant_inactive": {
    action: "sign_in",
    detail: "Grant is no longer active",
    audience: "developer",
    description: "The grant behind the token was revoked or expired, or its user was suspended.",
  },
  "agent_access.invalid_date": {
    action: "fix_input",
    detail: "{name} must be an ISO 8601 date or datetime",
    audience: "developer",
    description: "A tool's date bound does not parse as an ISO 8601 date.",
  },
  "agent_access.query_required": {
    action: "fix_input",
    detail: "query is required",
    audience: "developer",
    description: "A search tool was called with an empty query.",
  },
  "agent_access.query_too_short": {
    action: "fix_input",
    detail:
      "query needs at least one word of {min_length} letters or more; shorter words are ignored",
    audience: "developer",
    description: "Every word of a search query is shorter than the search indexes.",
  },
  "agent_access.message_required": {
    action: "fix_input",
    detail: "message is required",
    audience: "developer",
    description: "The report-issue tool was called with an empty message.",
  },
  "agent_access.name_description_required": {
    action: "fix_input",
    detail: "name and description are required",
    audience: "developer",
    description: "The request-tool tool was called without a name or description.",
  },
} as const satisfies Codes<"agent_access">;
