// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/index.ts.
// Do not edit: change the platform file and run the script.
import { access } from "./access.gen";
import { account } from "./account.gen";
import { agent } from "./agent.gen";
import { agent_access } from "./agent_access.gen";
import { analysis } from "./analysis.gen";
import { announcement } from "./announcement.gen";
import { auth } from "./auth.gen";
import { billing } from "./billing.gen";
import { canvas } from "./canvas.gen";
import { chat } from "./chat.gen";
import { conversation } from "./conversation.gen";
import { demo } from "./demo.gen";
import { document } from "./document.gen";
import { feedback } from "./feedback.gen";
import { field } from "./field.gen";
import { internal } from "./internal.gen";
import { invite } from "./invite.gen";
import { map } from "./map.gen";
import { member } from "./member.gen";
import { memory } from "./memory.gen";
import { notification } from "./notification.gen";
import { offer } from "./offer.gen";
import { organisation } from "./organisation.gen";
import { participant } from "./participant.gen";
import { popcorn } from "./popcorn.gen";
import { present } from "./present.gen";
import { pricing } from "./pricing.gen";
import { privacy } from "./privacy.gen";
import { project } from "./project.gen";
import { question } from "./question.gen";
import { rate_limit } from "./rate_limit.gen";
import { report } from "./report.gen";
import { request } from "./request.gen";
import { staff } from "./staff.gen";
import { tag } from "./tag.gen";
import { task } from "./task.gen";
import { template } from "./template.gen";
import { training } from "./training.gen";
import type { CodeSpec, ErrorAudience, SpecParams } from "./types.gen";
import { upload } from "./upload.gen";
import { validation } from "./validation.gen";
import { verify } from "./verify.gen";
import { webhook } from "./webhook.gen";
import { workspace } from "./workspace.gen";

/**
 * Every error code the platform sends, one file per namespace. A code is stable: clients
 * key their messages on it, so a code is renamed only with its frontend message.
 */
export const ERROR_CATALOG = {
  ...request,
  ...field,
  ...validation,
  ...auth,
  ...access,
  ...internal,
  ...rate_limit,
  ...account,
  ...invite,
  ...member,
  ...organisation,
  ...workspace,
  ...project,
  ...template,
  ...tag,
  ...webhook,
  ...conversation,
  ...upload,
  ...participant,
  ...chat,
  ...memory,
  ...agent,
  ...agent_access,
  ...canvas,
  ...report,
  ...analysis,
  ...map,
  ...present,
  ...popcorn,
  ...verify,
  ...feedback,
  ...notification,
  ...announcement,
  ...training,
  ...billing,
  ...pricing,
  ...document,
  ...task,
  ...offer,
  ...demo,
  ...staff,
  ...privacy,
  ...question,
} as const;

export type ErrorCatalog = typeof ERROR_CATALOG;
export type ErrorCode = keyof ErrorCatalog;
export type ErrorParams<C extends ErrorCode> = SpecParams<ErrorCatalog[C]>;
export type ErrorNamespace = ErrorCode extends `${infer N}.${string}` ? N : never;

type AudienceOf<S extends CodeSpec> = S extends { audience: infer A extends ErrorAudience }
  ? A
  : "user";

/** The codes a person can see on their own screen: each needs a frontend message. */
export type UserErrorCode = {
  [C in ErrorCode]: AudienceOf<ErrorCatalog[C]> extends "user" ? C : never;
}[ErrorCode];

/** The field-level codes a validation error lists per field. */
export type FieldErrorCode = Extract<ErrorCode, `field.${string}`>;

export * from "./types.gen";
