// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/notification.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

export const notification = {
  "notification.not_found": {
    action: "none",
    detail: "Notification not found",
    description: "The notification does not exist or belongs to someone else.",
  },
} as const satisfies Codes<"notification">;
