// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/organisation.ts.
// Do not edit: change the platform file and run the script.
import { type Codes, EM_DASH } from "./types.gen";

export const organisation = {
  "organisation.not_found": {
    action: "none",
    detail: "Organisation not found",
    description: "The organisation does not exist, was deleted, or the caller cannot see it.",
  },
  "organisation.no_access": {
    action: "contact_admin",
    detail: "No access to this organisation",
    params: ["admin_name", "admin_email"],
    description: "The caller is not a member of the organisation.",
  },
  "organisation.admin_only": {
    action: "contact_admin",
    detail: "Organisation admins or owners only",
    params: ["admin_name", "admin_email"],
    description: "The action needs an organisation admin or owner.",
  },
  "organisation.deleted": {
    action: "none",
    detail: "Organisation no longer exists",
    description: "The organisation an invite or link points at was deleted.",
  },
  "organisation.owner_only": {
    action: "contact_admin",
    detail: "Owner-only action",
    params: ["admin_name", "admin_email"],
    description: "The action needs an organisation owner.",
  },
  "organisation.not_member": {
    action: "contact_admin",
    detail: "Not a member of this organisation",
    params: ["admin_name", "admin_email"],
    description:
      "The caller asked to join or act in a workspace of an organisation they are not in.",
  },
  "organisation.billing_role_only": {
    action: "contact_admin",
    detail: "Organisation admin or billing role only",
    params: ["admin_name", "admin_email"],
    description: "Financial pages need an organisation admin, owner or billing member.",
  },
  "organisation.name_required": {
    action: "fix_input",
    detail: "Organisation name is required",
    description: "An organisation was created or renamed with an empty name.",
  },
  "organisation.external_cannot_manage": {
    action: "fix_input",
    detail: `This person is an external on one of the organisation's workspaces. Clear that first ${EM_DASH} they can't hold organisation admin/owner while marked as external.`,
    description:
      "Someone marked external on one of the organisation's workspaces was made organisation admin or owner.",
  },
  "organisation.no_billing_account": {
    action: "contact_support",
    detail: "organisation has no valid billing account",
    description:
      "The organisation's pooled billing account is missing or deleted, so no workspace can be added to it.",
  },
  "organisation.billing_canceled": {
    action: "upgrade",
    detail: "organisation billing is canceled; reactivate it to add workspaces",
    description:
      "The organisation's billing is canceled; a workspace cannot join its pooled plan until it is reactivated.",
  },
} as const satisfies Codes<"organisation">;
