// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/tag.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

export const tag = {
  "tag.not_found": {
    action: "none",
    detail: "Tag not found",
    description: "The tag does not exist or belongs to another project.",
  },
} as const satisfies Codes<"tag">;
