// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/verify.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

/** Verify: the portal step where participants confirm artefacts drawn from their conversation. */
export const verify = {
  "verify.not_enabled": {
    action: "contact_admin",
    detail: "Verify is not enabled for this project",
    description: "The project's Verify feature is switched off.",
  },
  "verify.topic_not_found": {
    action: "none",
    detail: "Custom topic not found for this project",
    description: "The custom Verify topic does not exist on this project.",
  },
  "verify.topic_unknown": {
    action: "none",
    detail: "Verification topic '{topic}' not found",
    description: "An artefact was asked for a topic key the project does not offer.",
  },
  "verify.artifact_id_required": {
    action: "fix_input",
    detail: "The artifact_id field is required.",
    audience: "developer",
    description: "An artefact action named no artefact.",
  },
  "verify.artifact_not_found": {
    action: "none",
    detail: "Artifact not found",
    description: "The artefact does not exist or was deleted.",
  },
  "verify.artifact_wrong_conversation": {
    action: "none",
    detail: "The artifact does not belong to this conversation",
    audience: "developer",
    description: "An artefact update named a conversation the artefact is not part of.",
  },
  "verify.no_chunks": {
    action: "wait",
    detail: "Conversation has no chunks yet",
    description:
      "An artefact was asked for before any of the conversation reached the server; details.code is NO_CHUNKS.",
  },
  "verify.no_new_feedback": {
    action: "none",
    detail: "No new feedback found since provided timestamp",
    description:
      "A revision was asked for, but the participant said nothing new since the artefact was made; details.code is NO_NEW_FEEDBACK.",
  },
  "verify.generation_failed": {
    action: "retry",
    detail: "Failed to generate verification artifact",
    description:
      "The model call behind an artefact (made or revised) failed; sent as a 500 with the old text.",
  },
  "verify.content_conflict": {
    action: "fix_input",
    detail: "Provide either useConversation or content, not both",
    audience: "developer",
    description: "An artefact update sent both new content and a request to regenerate it.",
  },
} as const satisfies Codes<"verify">;
