// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/webhook.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

export const webhook = {
  "webhook.not_found": {
    action: "none",
    detail: "Webhook not found",
    description: "The webhook does not exist or belongs to another project.",
  },
  "webhook.invalid_event": {
    action: "fix_input",
    detail: "Invalid event type: {event}. Valid types: {valid}",
    description: "A webhook subscribed to an event name that does not exist.",
  },
  "webhook.invalid_url": {
    action: "fix_input",
    detail: "URL must start with http:// or https://",
    description: "The webhook URL is not an http or https address.",
  },
  "webhook.target_not_allowed": {
    action: "fix_input",
    detail: "Webhook URL points to a private or internal address",
    description:
      "The webhook URL is invalid, does not resolve, or points at a private address; detail says which.",
  },
  "webhook.invalid_status": {
    action: "fix_input",
    detail: "Status must be one of: published, draft, archived",
    description: "A webhook status outside published, draft and archived.",
  },
  "webhook.invalid_target": {
    action: "fix_input",
    detail: "Target must be url with a URL, or sam_inbox with one of: {codes}",
    description:
      "Staff set a webhook target other than url with a URL or sam_inbox with an allowed code.",
  },
  "webhook.sam_inbox_unavailable": {
    action: "none",
    detail: "sam's inbox is not configured here, or a webhook aimed at it cannot be tested",
    description:
      "The deployment has no SAM_INBOX_* settings, or the test button was pressed on a webhook that delivers to sam's inbox, where a sample would post to a real channel.",
  },
} as const satisfies Codes<"webhook">;
