// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/workspace.ts.
// Do not edit: change the platform file and run the script.
import { type Codes, EM_DASH } from "./types.gen";

export const workspace = {
  "workspace.not_found": {
    action: "none",
    detail: "Workspace not found",
    description: "The workspace does not exist, was deleted, or the caller cannot see it.",
  },
  "workspace.no_access": {
    action: "contact_admin",
    detail: "No access to this workspace",
    params: ["admin_name", "admin_email"],
    description: "The caller is not a member of the workspace.",
  },
  "workspace.deleted": {
    action: "none",
    detail: "Workspace no longer exists",
    description: "The workspace an invite or link points at was deleted.",
  },
  "workspace.logo_url_too_long": {
    action: "fix_input",
    detail: "Logo URL is too long",
    description: "The workspace logo link is longer than the column allows.",
  },
  "workspace.logo_url_invalid": {
    action: "fix_input",
    detail: "Logo URL must start with http:// or https://",
    description: "The workspace logo link is not an http or https address.",
  },
  "workspace.data_ownership_admin_only": {
    action: "contact_admin",
    detail: "Only an organisation admin can change data ownership",
    params: ["admin_name", "admin_email"],
    description:
      "Changing whether a workspace is internal or for an external client needs an org admin.",
  },
  "workspace.external_needs_owner": {
    action: "fix_input",
    detail: "An external workspace needs an owning organisation name and a data owner email.",
    description: "A workspace was marked external without naming who owns its data.",
  },
  "workspace.data_owner_org_required": {
    action: "fix_input",
    detail: "The owning organisation's name is required when you name a data owner.",
    description: "A new workspace named a data owner email but no owning organisation.",
  },
  "workspace.partner_agreement_required": {
    action: "fix_input",
    detail: "You must accept the partner agreement to mark this workspace as external.",
    description:
      "Marking a workspace external, or creating an external-client one, needs the partner agreement accepted.",
  },
  "workspace.data_owner_is_member": {
    action: "fix_input",
    detail:
      "That data owner is already a member of your organisation. External-client workspaces need a data owner outside your organisation.",
    description:
      "The data owner email of an external-client workspace belongs to a member of the organisation.",
  },
  "workspace.paid_rescope": {
    action: "contact_support",
    detail:
      "This workspace has active or paid billing attached, so its internal/external classification can't be changed automatically. Reach out to your account manager to move the billing first.",
    description:
      "Switching internal/external would move paid or subscribed billing; a person has to do it.",
  },
  "workspace.visibility_requires_tier": {
    action: "upgrade",
    detail:
      "Invite-only and private workspaces require the Innovator plan or above. Create the workspace as open, then change its visibility after upgrading.",
    description: "A free plan asked for an invite-only or private workspace.",
  },
  "workspace.create_admin_only": {
    action: "contact_admin",
    detail: "You must be an organisation admin or owner to create a workspace here.",
    params: ["admin_name", "admin_email"],
    description: "A plain organisation member tried to create a workspace.",
  },
  "workspace.delete_admin_only": {
    action: "contact_admin",
    detail: "Only a workspace admin or owner can delete this workspace",
    params: ["admin_name", "admin_email"],
    description: "A member without the admin role tried to delete the workspace.",
  },
  "workspace.has_projects": {
    action: "fix_input",
    detail: `This workspace has {count} project(s). Delete or move them first ${EM_DASH} you can do this from the organisation's Projects view.`,
    params: ["count"],
    description: "A workspace with projects cannot be deleted until they are deleted or moved.",
  },
  "workspace.tier_change_active_subscription": {
    action: "none",
    detail:
      "This account has an active subscription. Ask the customer to cancel it from their billing page before you change the tier.",
    audience: "staff",
    description:
      "Staff tried to set the tier of a workspace whose billing has a live Mollie subscription.",
  },
  "workspace.unknown_tier": {
    action: "contact_support",
    detail: "Unknown tier value",
    audience: "developer",
    description: "A stored or requested tier is not in the tier ladder; sent as a 500.",
  },
  "workspace.no_billing_org": {
    action: "contact_support",
    detail: "Workspace has no billing organisation set",
    audience: "developer",
    description:
      "A workspace handoff found no billing organisation on the workspace; sent as a 500.",
  },
  "workspace.handoff_shared_plan": {
    action: "none",
    detail:
      "This workspace is billed under its organisation's shared plan, so it can't be handed off. Only workspaces billed on their own (for an external client) can be transferred.",
    description: "A handoff was asked for a workspace on its organisation's pooled billing.",
  },
  "workspace.handoff_admin_only": {
    action: "contact_admin",
    detail: "Only the billing organisation's admins can initiate handoff",
    params: ["admin_name", "admin_email"],
    description:
      "A handoff was started by someone who is not an admin of the billing organisation.",
  },
  "workspace.handoff_same_org": {
    action: "fix_input",
    detail: "Target organisation is already the billing organisation",
    description: "A handoff named the organisation that already bills the workspace.",
  },
  "workspace.handoff_target_not_found": {
    action: "fix_input",
    detail: "Target organisation not found",
    description: "The organisation a handoff names does not exist or was deleted.",
  },
  "workspace.handoff_pending": {
    action: "none",
    detail: "A handoff is already pending on this workspace",
    description: "A second handoff was started while one waits for acceptance.",
  },
  "workspace.handoff_none_pending": {
    action: "none",
    detail: "No pending handoff on this workspace",
    description: "A handoff was accepted or cancelled when none was pending.",
  },
  "workspace.handoff_inconsistent": {
    action: "contact_support",
    detail: `Pending handoff has no target organisation ${EM_DASH} inconsistent state`,
    audience: "developer",
    description: "A pending handoff row has no target organisation; sent as a 500.",
  },
  "workspace.handoff_accept_target_admin_only": {
    action: "contact_admin",
    detail: "Only the target organisation's admins can accept this handoff",
    params: ["admin_name", "admin_email"],
    description:
      "Someone who is not an admin of the receiving organisation tried to accept a handoff.",
  },
  "workspace.handoff_cancel_initiator_only": {
    action: "contact_admin",
    detail: "Only the initiating organisation's admins can cancel",
    params: ["admin_name", "admin_email"],
    description:
      "Someone who is not an admin of the initiating organisation tried to cancel a handoff.",
  },
  "workspace.access_request_not_found": {
    action: "none",
    detail: "Request not found",
    description: "The access request (or support access request) does not exist on this workspace.",
  },
  "workspace.access_request_actioned": {
    action: "none",
    detail: "Request already actioned",
    description: "An access request was approved or declined twice.",
  },
  "workspace.removed_from": {
    action: "contact_admin",
    detail: "You were removed from this workspace. Ask a workspace admin to invite you back.",
    params: ["admin_name", "admin_email"],
    description:
      "Someone removed from the workspace asked to rejoin; only a new invite lets them in.",
  },
  "workspace.private": {
    action: "contact_admin",
    detail: "This workspace is private. Ask a workspace admin to invite you.",
    params: ["admin_name", "admin_email"],
    description: "An access request was made on a private workspace, which only takes invites.",
  },
  "workspace.admin_joins_directly": {
    action: "none",
    detail: "Organisation admins can join directly, no approval needed",
    description: "An organisation admin asked for access they can take themselves.",
  },
  "workspace.support_request_handled": {
    action: "none",
    detail: "Request is already {status}.",
    description:
      "A staff support access request was approved or declined after it was already decided.",
  },
  "workspace.support_request_expired": {
    action: "none",
    detail: "Request expired.",
    description: "A staff support access request was answered after it expired.",
  },
} as const satisfies Codes<"workspace">;
