// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/billing.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

export const billing = {
  "billing.role_required": {
    action: "contact_admin",
    detail: "You must be an organisation owner, admin, or billing role.",
    params: ["admin_name", "admin_email"],
    description: "Billing pages need an organisation owner, admin or billing member.",
  },
  "billing.account_not_found": {
    action: "none",
    detail: "Billing account not found",
    description: "The billing account does not exist or was deleted.",
  },
  "billing.invoice_pdf_missing": {
    action: "retry",
    detail: "No PDF available for this invoice",
    description: "Mollie has no PDF for the invoice (yet).",
  },
  "billing.webhook_failed": {
    action: "retry",
    detail: "webhook processing failed",
    audience: "developer",
    description: "The Mollie webhook could not be processed; the 500 makes Mollie retry.",
  },
  "billing.tax_id_required": {
    action: "fix_input",
    detail: "Give at least one of the VAT, KvK or KBO number",
    description: "Billing details were saved without any company registration or VAT number.",
  },
  "billing.request_failed": {
    action: "contact_support",
    detail: "{reason}",
    description: "A billing operation was refused for a reason no more specific code names.",
  },
  "billing.payments_unavailable": {
    action: "contact_support",
    detail: "Mollie is not configured",
    description: "This environment has no Mollie key, so no payment can start.",
  },
  "billing.tier_not_payable": {
    action: "contact_support",
    detail: "tier {tier} is not payable",
    audience: "developer",
    description: "A price was asked for a tier that has no monthly price.",
  },
  "billing.tier_not_purchasable": {
    action: "contact_support",
    detail: "tier {tier} is not available for checkout",
    description: "Checkout was started for a tier that cannot be bought online.",
  },
  "billing.already_subscribed": {
    action: "none",
    detail: "this account already has an active subscription",
    description: "Checkout was started for an account that already has an active subscription.",
  },
  "billing.checkout_failed": {
    action: "retry",
    detail: "Mollie did not return a checkout URL",
    description: "Mollie answered without a checkout URL.",
  },
  "billing.payment_link_failed": {
    action: "retry",
    detail: "Mollie did not return a payment link URL",
    audience: "staff",
    description: "Mollie answered without a payment link URL.",
  },
  "billing.no_payment_profile": {
    action: "none",
    detail: "no payment profile to update; subscribe first",
    description: "The payment method was updated for an account that never subscribed.",
  },
  "billing.no_invoice_amount": {
    action: "none",
    detail: "no invoice amount for this account",
    audience: "staff",
    description: "A managed account has no invoice amount to charge.",
  },
  "billing.account_manager_not_found": {
    action: "fix_input",
    detail: "Account manager user not found",
    audience: "staff",
    description: "The account manager id names no user.",
  },
  "billing.account_manager_not_staff": {
    action: "fix_input",
    detail: "Account manager must be a dembrane staff member (@dembrane.com).",
    audience: "staff",
    description: "Only a dembrane.com user can be an account manager.",
  },
  "billing.no_billing_account": {
    action: "none",
    detail: "This organisation has no billing account yet",
    audience: "staff",
    description: "The organisation has no billing account to set an account manager on.",
  },
  "billing.invoice_total_mismatch": {
    action: "fix_input",
    detail: "subtotal_cents plus vat_cents must equal total_cents",
    audience: "staff",
    description: "A pushed invoice's amounts do not add up.",
  },
  "billing.invoice_other_organisation": {
    action: "none",
    detail: "This Exact invoice belongs to another organisation",
    audience: "staff",
    description: "The Exact invoice id is already recorded for another organisation.",
  },
  "billing.invoice_immutable": {
    action: "none",
    detail:
      "An invoice's number, dates and amounts cannot change; void it in Exact and push the new one",
    audience: "staff",
    description: "A pushed invoice differs from the recorded one in number, dates or amounts.",
  },
  "billing.tier_limit": {
    action: "upgrade",
    detail: "Free tier limit",
    params: ["limit", "organisation_id"],
    description:
      "The free tier's limit for this feature is used up. limit names which: chats, chat_turns, report or workspaces.",
  },
  "billing.tier_required": {
    action: "upgrade",
    detail: "This action requires the {required} tier (currently {tier}).",
    params: ["organisation_id"],
    description: "The feature needs a higher plan than the organisation has.",
  },
  "billing.plan_inactive": {
    action: "upgrade",
    detail: "Reactivate your plan to add members.",
    params: ["organisation_id"],
    description: "The organisation's plan lapsed; adding members waits until it is reactivated.",
  },
  "billing.seat_pricing_unavailable": {
    action: "retry",
    detail: "Seat pricing is temporarily unavailable",
    description: "The seat price could not be computed (Mollie or the price table did not answer).",
  },
} as const satisfies Codes<"billing">;
