// Generated by scripts/sync-error-codes.mjs from platform/packages/core/src/catalog/demo.ts.
// Do not edit: change the platform file and run the script.
import type { Codes } from "./types.gen";

/** Prospect demos and the accounts made from a needs form, run by staff and sam. */
export const demo = {
  "demo.not_found": {
    action: "none",
    detail: "Demo not found",
    audience: "staff",
    description: "The demo does not exist.",
  },
  "demo.website_invalid": {
    action: "fix_input",
    detail: "website_url must be a web address",
    audience: "staff",
    description: "The prospect's website is not an http or https address.",
  },
  "demo.retry_not_failed": {
    action: "none",
    detail: "Only a failed demo can be retried",
    audience: "staff",
    description: "Retry was asked for a demo that did not fail.",
  },
  "demo.publish_not_draft": {
    action: "none",
    detail: "Only a finished draft can be published",
    audience: "staff",
    description: "Publish was asked for a demo that is not a finished draft.",
  },
  "demo.contact_not_created": {
    action: "retry",
    detail: "The contact was not created",
    audience: "staff",
    description: "Building the demo account did not produce the contact person.",
  },
  "demo.not_configured": {
    action: "contact_support",
    detail: "Demos are not configured here",
    audience: "staff",
    description: "This environment has no demo settings.",
  },
  "demo.contact_email_invalid": {
    action: "fix_input",
    detail: "contact_email is not an email address",
    audience: "staff",
    description: "The prospect's contact email fails the syntax check.",
  },
  "demo.needs_form_not_found": {
    action: "fix_input",
    detail: "No needs form with that reference",
    audience: "staff",
    description: "No pricing configuration matches the given WEB- or DEM- reference.",
  },
  "demo.organisation_deleted": {
    action: "none",
    detail: "That organisation was deleted",
    audience: "staff",
    description: "The prospect's organisation exists but is deleted.",
  },
} as const satisfies Codes<"demo">;
