import {
  ARGS_READY,
  ASSESSED,
  ana,
  EDITED,
  FAILED_RUN,
  FEEDBACK,
  LAST_OPENED,
  QUEUED_RUN,
  WITHDRAWN,
} from "../analysis-setup";
import { projects } from "../fixtures";
import { P2_OPEN } from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p1, p2, legacy } = projects;
const A = "/api/v2/bff/analysis";
const obj = (i: number) => ana.objects[i] as string;
const rev = (i: number) => ana.revisions[i] as string;

// Model-free recipes and request paths only: nothing here waits on a worker, so both sides
// leave the same queued rows. Generated fields do not appear in these responses.
export default scenarios([
  // ── recipes ───────────────────────────────────────────────────────
  { name: "analysis recipes: signed in", as: "alice", method: "GET", path: `${A}/recipes` },
  { name: "analysis recipes: anonymous", as: "anonymous", method: "GET", path: `${A}/recipes` },

  // ── run requests ──────────────────────────────────────────────────
  {
    name: "analysis run: arguments on a project with transcripts",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments" },
  },
  {
    name: "analysis run: refresh over a ready output with other inputs computes again",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", scope_key: "project", mode: "refresh" },
    setup: ARGS_READY,
  },
  {
    name: "analysis run: a known client key answers with its run",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", idempotency_key: "parity-key-queued" },
    setup: [...ARGS_READY, ...QUEUED_RUN],
  },
  {
    name: "analysis run: regenerate",
    as: "erin",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", mode: "regenerate", idempotency_key: "parity-regen-1" },
    setup: ARGS_READY,
  },
  {
    name: "analysis run: tensions pins a compatible ready arguments output",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "tensions", parameters: { input_set: "arguments" } },
    setup: ARGS_READY,
  },
  {
    name: "analysis run: tensions without arguments waits for them",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "tensions", parameters: { input_set: "arguments" } },
    // A waiting run's fingerprint hashes the id of the dependency run it waits on, which
    // each side mints anew; every other column is compared.
    ignoreFields: ["request_fingerprint"],
  },
  {
    name: "analysis run: tensions needs its parameter",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "tensions" },
  },
  {
    name: "analysis run: deduplication with a threshold",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "deduplicated_arguments", parameters: { similarity_threshold: 0.85 } },
    setup: ARGS_READY,
  },
  {
    name: "analysis run: deduplication refuses an out of range threshold",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "deduplicated_arguments", parameters: { similarity_threshold: 1.5 } },
  },
  {
    name: "analysis run: integration fixture over selected revisions",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: {
      recipe_id: "integration.fixture_delivery",
      scope_key: "delivery:acme",
      selected_revision_ids: [rev(0), rev(1)],
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis run: a selected revision outside the project",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: {
      recipe_id: "integration.fixture_delivery",
      scope_key: "delivery:acme",
      selected_revision_ids: ["00000000-0000-4000-8000-000000000999"],
    },
  },
  {
    name: "analysis run: retry the latest failed run",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", mode: "retry" },
    setup: [...ARGS_READY, ...FAILED_RUN],
  },
  {
    name: "analysis run: retry with nothing failed",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", mode: "retry" },
    setup: ARGS_READY,
  },
  {
    name: "analysis run: unknown recipe",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "nope" },
  },
  {
    name: "analysis run: internal recipe refused",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "map.fact_check_assessment", scope_key: `revision:${rev(0)}` },
  },
  {
    name: "analysis run: scope the recipe does not accept",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", scope_key: "conversation:x" },
  },
  {
    name: "analysis run: parameters for a recipe that takes none",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments", parameters: { x: 1 } },
  },
  {
    name: "analysis run: body validation",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: {
      scope_key: "",
      mode: "sometimes",
      idempotency_key: "short",
      selected_revision_ids: "x",
    },
  },
  {
    name: "analysis run: observer may not run",
    as: "rita",
    method: "POST",
    path: `${A}/projects/${p2}/runs`,
    body: { recipe_id: "arguments" },
    setup: [P2_OPEN],
  },
  {
    name: "analysis run: other tenant",
    as: "bob",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments" },
  },
  {
    name: "analysis run: not onboarded",
    as: "dave",
    method: "POST",
    path: `${A}/projects/${legacy}/runs`,
    body: { recipe_id: "arguments" },
  },
  {
    name: "analysis run: staff without membership",
    as: "admin",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments" },
  },
  {
    name: "analysis run: anonymous",
    as: "anonymous",
    method: "POST",
    path: `${A}/projects/${p1}/runs`,
    body: { recipe_id: "arguments" },
  },

  // ── runs read and cancel ──────────────────────────────────────────
  {
    name: "analysis run read: with steps",
    as: "alice",
    method: "GET",
    path: `${A}/runs/${ana.run}`,
    setup: ARGS_READY,
  },
  { name: "analysis run read: not an id", as: "alice", method: "GET", path: `${A}/runs/abc` },
  { name: "analysis run read: unknown", as: "alice", method: "GET", path: `${A}/runs/${ana.run}` },
  {
    name: "analysis run read: other tenant",
    as: "bob",
    method: "GET",
    path: `${A}/runs/${ana.run}`,
    setup: ARGS_READY,
  },
  {
    name: "analysis runs: project history",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/runs`,
    setup: [...ARGS_READY, ...FAILED_RUN],
  },
  {
    name: "analysis runs: paged",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/runs`,
    query: { offset: "1", limit: "1" },
    setup: [...ARGS_READY, ...FAILED_RUN],
  },
  {
    name: "analysis runs: limit out of range",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/runs`,
    query: { limit: "0", offset: "-1" },
  },
  {
    name: "analysis runs: observer reads, may not run",
    as: "rita",
    method: "GET",
    path: `${A}/projects/${p2}/runs`,
    setup: [P2_OPEN],
  },
  {
    name: "analysis run cancel: queued",
    as: "alice",
    method: "POST",
    path: `${A}/runs/${ana.queuedRun}/cancel`,
    setup: [...ARGS_READY, ...QUEUED_RUN],
  },
  {
    name: "analysis run cancel: a ready run stays ready",
    as: "alice",
    method: "POST",
    path: `${A}/runs/${ana.run}/cancel`,
    setup: ARGS_READY,
  },
  {
    name: "analysis run cancel: other tenant",
    as: "bob",
    method: "POST",
    path: `${A}/runs/${ana.queuedRun}/cancel`,
    setup: [...ARGS_READY, ...QUEUED_RUN],
  },

  // ── objects ───────────────────────────────────────────────────────
  {
    name: "analysis objects: current map",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    setup: ARGS_READY,
  },
  {
    name: "analysis objects: no map yet",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
  },
  {
    name: "analysis objects: one type, paged",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { type: "argument", offset: "1", limit: "1" },
    setup: ARGS_READY,
  },
  {
    name: "analysis objects: unknown type",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { type: "poem" },
  },
  {
    name: "analysis objects: bad membership and sort",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { membership: "gone", sort: "loud" },
  },
  {
    name: "analysis objects: withdrawn only",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { membership: "withdrawn" },
    setup: [...ARGS_READY, ...WITHDRAWN],
  },
  {
    name: "analysis objects: all memberships",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { membership: "all" },
    setup: [...ARGS_READY, ...WITHDRAWN],
  },
  {
    name: "analysis objects: attention order",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { sort: "attention" },
    setup: [...ARGS_READY, ...EDITED, LAST_OPENED, FEEDBACK, ...ASSESSED],
  },
  {
    name: "analysis objects: a pinned snapshot",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { snapshot_id: ana.snapshot },
    setup: ARGS_READY,
  },
  {
    name: "analysis objects: snapshot of nothing",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { snapshot_id: ana.run },
    setup: ARGS_READY,
  },
  {
    name: "analysis objects: one producer's output",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { scope: "arguments@project" },
    setup: ARGS_READY,
  },
  {
    name: "analysis objects: unknown producer",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    query: { scope: "stakeholders" },
    setup: ARGS_READY,
  },
  {
    name: "analysis objects: other tenant",
    as: "bob",
    method: "GET",
    path: `${A}/projects/${p1}/objects`,
    setup: ARGS_READY,
  },
  {
    name: "analysis object history",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects/${obj(1)}/revisions`,
    setup: [...ARGS_READY, ...EDITED],
  },
  {
    name: "analysis object history: unknown object",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/objects/${ana.run}/revisions`,
    setup: ARGS_READY,
  },

  // ── host edits ────────────────────────────────────────────────────
  {
    name: "analysis edit: reword by patch",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: {
      expected_revision_id: rev(0),
      patch: { statement: "Charging points near the flats have a waiting list of months." },
      reason: "clearer wording",
      change_kind: "clarity",
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: reword by whole payload",
    as: "erin",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(2)}/revisions`,
    body: {
      expected_revision_id: rev(2),
      payload: {
        statement: "  Cycle lanes should carry on past the ring road. ",
        epistemicKind: "argument",
        valence: "negative",
        evidence: [
          {
            conversationId: "c1000000-0000-4000-8000-000000000002",
            label: "Resident 2",
            createdAt: "2026-09-27T15:41:55.310Z",
            quotes: ["the cycle lanes end abruptly at the ring road"],
          },
        ],
      },
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: grounds may not change",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(2)}/revisions`,
    body: {
      expected_revision_id: rev(2),
      payload: {
        statement: "Cycle lanes should continue past the ring road.",
        epistemicKind: "claim",
        valence: "negative",
      },
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: a patch of a field that is not words",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: { expected_revision_id: rev(0), patch: { valence: "positive", statement: "x" } },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: payload and patch together",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: { expected_revision_id: rev(0), patch: { statement: "x" }, payload: { statement: "y" } },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: meaning needs a reason",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: {
      expected_revision_id: rev(0),
      patch: { statement: "Something else." },
      change_kind: "meaning",
      reason: "short",
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: an empty statement fails its schema",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: { expected_revision_id: rev(0), patch: { statement: "   " } },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: the head moved on",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(1)}/revisions`,
    body: { expected_revision_id: rev(1), patch: { statement: "My own wording." } },
    setup: [...ARGS_READY, ...EDITED],
  },
  {
    name: "analysis edit: unknown expected revision",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: { expected_revision_id: rev(1), patch: { statement: "x" } },
    setup: ARGS_READY,
  },
  {
    name: "analysis edit: a read-only type",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${ana.assessmentObject}/revisions`,
    body: { expected_revision_id: ana.assessment, patch: { verdict: "true" } },
    setup: [...ARGS_READY, ...ASSESSED],
  },
  {
    name: "analysis edit: unknown object",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/nope/revisions`,
    body: { expected_revision_id: rev(0), patch: { statement: "x" } },
  },
  {
    name: "analysis edit: body validation",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/revisions`,
    body: { patch: "x", change_kind: "a-very-long-kind-of-change" },
  },
  {
    name: "analysis edit: observer",
    as: "rita",
    method: "POST",
    path: `${A}/projects/${p2}/objects/${obj(0)}/revisions`,
    body: { expected_revision_id: rev(0), patch: { statement: "x" } },
    setup: [P2_OPEN],
  },
  {
    name: "analysis rollback: to the generated wording",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(1)}/rollback`,
    body: {
      expected_revision_id: ana.edit,
      to_revision_id: rev(1),
      reason: "back to the source",
      change_kind: "rollback",
    },
    setup: [...ARGS_READY, ...EDITED],
  },
  {
    name: "analysis rollback: target of another object",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(1)}/rollback`,
    body: { expected_revision_id: ana.edit, to_revision_id: rev(0) },
    setup: [...ARGS_READY, ...EDITED],
  },
  {
    name: "analysis membership: withdraw",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/membership`,
    body: {
      expected_revision_id: rev(0),
      excluded: true,
      reason: "dup #2",
      change_kind: "withdraw",
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis membership: restore",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(2)}/membership`,
    body: { expected_revision_id: ana.withdrawal, excluded: false, change_kind: "restore" },
    setup: [...ARGS_READY, ...WITHDRAWN],
  },
  {
    name: "analysis membership: withdraw recorded as a wording change",
    as: "alice",
    method: "POST",
    path: `${A}/projects/${p1}/objects/${obj(0)}/membership`,
    body: { expected_revision_id: rev(0), excluded: true, change_kind: "typo" },
    setup: ARGS_READY,
  },

  // ── last opened and thumbs ────────────────────────────────────────
  {
    name: "analysis last-opened: never",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/results/last-opened`,
  },
  {
    name: "analysis last-opened: recorded",
    as: "alice",
    method: "GET",
    path: `${A}/projects/${p1}/results/last-opened`,
    setup: [LAST_OPENED],
  },
  {
    name: "analysis last-opened: mark now",
    as: "alice",
    method: "PUT",
    path: `${A}/projects/${p1}/results/last-opened`,
    ignoreFields: ["openedAt"],
    setup: [LAST_OPENED],
  },
  {
    name: "analysis last-opened: other tenant",
    as: "bob",
    method: "PUT",
    path: `${A}/projects/${p1}/results/last-opened`,
  },
  {
    name: "analysis feedback: thumbs up with reasons",
    as: "alice",
    method: "PUT",
    path: `${A}/projects/${p1}/objects/${obj(1)}/feedback`,
    body: {
      revision_id: rev(1),
      rating: "up",
      tags: ["relevant", "other", "relevant"],
      note: "  spot on  ",
    },
    setup: ARGS_READY,
  },
  {
    name: "analysis feedback: re-rate overwrites",
    as: "alice",
    method: "PUT",
    path: `${A}/projects/${p1}/objects/${obj(0)}/feedback`,
    body: { revision_id: rev(0), rating: "up", note: "dropped without other" },
    setup: [...ARGS_READY, FEEDBACK],
  },
  {
    name: "analysis feedback: a reason of the other thumb",
    as: "alice",
    method: "PUT",
    path: `${A}/projects/${p1}/objects/${obj(0)}/feedback`,
    body: { revision_id: rev(0), rating: "up", tags: ["tone_deaf"] },
    setup: ARGS_READY,
  },
  {
    name: "analysis feedback: revision of another object",
    as: "alice",
    method: "PUT",
    path: `${A}/projects/${p1}/objects/${obj(0)}/feedback`,
    body: { revision_id: rev(1), rating: "down" },
    setup: ARGS_READY,
  },
  {
    name: "analysis feedback: too many tags",
    as: "alice",
    method: "PUT",
    path: `${A}/projects/${p1}/objects/${obj(0)}/feedback`,
    body: { revision_id: rev(0), rating: "down", tags: ["a", "b", "c", "d", "e"] },
  },
  {
    name: "analysis feedback: take it back",
    as: "alice",
    method: "DELETE",
    path: `${A}/projects/${p1}/objects/${obj(0)}/feedback`,
    setup: [...ARGS_READY, FEEDBACK],
  },

  // ── lineage ───────────────────────────────────────────────────────
  {
    name: "analysis lineage: a pinned revision",
    as: "alice",
    method: "GET",
    path: `${A}/snapshots/${ana.snapshot}/revisions/${rev(1)}/lineage`,
    setup: ARGS_READY,
  },
  {
    name: "analysis lineage: not pinned",
    as: "alice",
    method: "GET",
    path: `${A}/snapshots/${ana.snapshot}/revisions/${ana.run}/lineage`,
    setup: ARGS_READY,
  },
  {
    name: "analysis lineage: unknown snapshot",
    as: "alice",
    method: "GET",
    path: `${A}/snapshots/${ana.run}/revisions/${rev(1)}/lineage`,
    setup: ARGS_READY,
  },
  {
    name: "analysis lineage: other tenant",
    as: "bob",
    method: "GET",
    path: `${A}/snapshots/${ana.snapshot}/revisions/${rev(1)}/lineage`,
    setup: ARGS_READY,
  },
]);
