import {
  AGENTIC_CHAT,
  C1_LOCKED,
  chat,
  NO_MODE_CHAT,
  P2_CHAT,
  P3_THREE_TURNS,
  PRIVATE_CHAT,
  UNCOUNTED_MESSAGE,
} from "../chat-setup";
import { chats, conversations, projects } from "../fixtures";
import { P2_OPEN } from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p1 } = projects;
const { c1, c2, c3 } = conversations;
const C = (id: string, rest = "") => `/api/chats/${id}${rest}`;
const MISSING = "c5000000-0000-4000-8000-0000000000ff";
// Chat writes the Python API made through its admin token stamped the Directus service
// account as user_updated; the port records the person who made the change.
const UPDATER = "updater: user_updated is the caller, not the Directus service account";
const M10 = "M-10: a private chat is its creator's; a colleague gets 404";
const H4 = "H-4: a conversation must belong to the chat's project in every mode";

export default scenarios([
  // ── DELETE /api/chats/{id} ────────────────────────────────────────
  {
    name: "chat delete: owner",
    as: "alice",
    method: "DELETE",
    path: C(chats.p1),
    differs: UPDATER,
  },
  { name: "chat delete: anonymous", as: "anonymous", method: "DELETE", path: C(chats.p1) },
  { name: "chat delete: other tenant", as: "bob", method: "DELETE", path: C(chats.p1) },
  { name: "chat delete: not onboarded", as: "dave", method: "DELETE", path: C(chats.p1) },
  { name: "chat delete: missing", as: "alice", method: "DELETE", path: C(MISSING) },
  { name: "chat delete: not a uuid", as: "alice", method: "DELETE", path: C("nope") },
  {
    name: "chat delete: observer refused",
    as: "rita",
    method: "DELETE",
    path: C(chat.p2),
    setup: [P2_OPEN, P2_CHAT],
  },
  {
    name: "chat delete: external (contributors may delete)",
    as: "bob",
    method: "DELETE",
    path: C(chat.p2),
    setup: [P2_OPEN, P2_CHAT],
    differs: UPDATER,
  },
  {
    name: "chat delete: colleague's private chat",
    as: "erin",
    method: "DELETE",
    path: C(chat.private),
    setup: PRIVATE_CHAT,
    differs: M10,
  },

  // ── GET context ───────────────────────────────────────────────────
  { name: "chat context: owner", as: "alice", method: "GET", path: C(chats.p1, "/context") },
  { name: "chat context: staff", as: "admin", method: "GET", path: C(chats.p1, "/context") },
  {
    name: "chat context: counts and stores a new message's tokens",
    as: "alice",
    method: "GET",
    path: C(chats.p1, "/context"),
    setup: UNCOUNTED_MESSAGE,
  },
  {
    name: "chat context: a used conversation is locked",
    as: "alice",
    method: "GET",
    path: C(chats.p1, "/context"),
    setup: C1_LOCKED,
  },
  {
    name: "chat context: empty chat",
    as: "alice",
    method: "GET",
    path: C(chat.noMode, "/context"),
    setup: NO_MODE_CHAT,
  },
  { name: "chat context: other tenant", as: "bob", method: "GET", path: C(chats.p1, "/context") },
  {
    name: "chat context: anonymous",
    as: "anonymous",
    method: "GET",
    path: C(chats.p1, "/context"),
  },
  { name: "chat context: missing", as: "alice", method: "GET", path: C(MISSING, "/context") },
  {
    name: "chat context: observer refused",
    as: "rita",
    method: "GET",
    path: C(chat.p2, "/context"),
    setup: [P2_OPEN, P2_CHAT],
  },

  // ── POST add-context ──────────────────────────────────────────────
  {
    name: "add-context: nothing given",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: {},
  },
  {
    name: "add-context: two options",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { conversation_id: c2, select_all: true },
  },
  {
    name: "add-context: bad boolean",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { select_all: "maybe" },
  },
  {
    name: "add-context: one conversation",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { conversation_id: c2 },
  },
  {
    name: "add-context: already in the chat",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { conversation_id: c1 },
  },
  {
    name: "add-context: missing conversation",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { conversation_id: MISSING },
  },
  {
    name: "add-context: another tenant's conversation",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { conversation_id: c3 },
    differs: H4,
  },
  {
    name: "add-context: another tenant's conversation into an agentic chat",
    as: "alice",
    method: "POST",
    path: C(chat.agentic, "/add-context"),
    body: { conversation_id: c3 },
    setup: AGENTIC_CHAT,
    differs: H4,
  },
  {
    name: "add-context: agentic chat skips the budget",
    as: "alice",
    method: "POST",
    path: C(chat.agentic, "/add-context"),
    body: { conversation_id: c2 },
    setup: AGENTIC_CHAT,
  },
  {
    name: "add-context: select all",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { select_all: true, project_id: p1 },
  },
  {
    name: "add-context: select all into an empty chat",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/add-context"),
    body: { select_all: true },
    setup: NO_MODE_CHAT,
  },
  {
    name: "add-context: select all, verified only",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/add-context"),
    body: { select_all: true, verified_only: true },
    setup: NO_MODE_CHAT,
  },
  {
    name: "add-context: select all, by tag",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/add-context"),
    body: { select_all: true, tag_ids: ["f2000000-0000-4000-8000-000000000001"] },
    setup: NO_MODE_CHAT,
  },
  {
    name: "add-context: select all, search",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/add-context"),
    body: { select_all: true, search_text: "resident 2" },
    setup: NO_MODE_CHAT,
  },
  {
    name: "add-context: explicit pick with strangers",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/add-context"),
    body: { conversation_ids: [c2, c3, c2, MISSING, c1] },
    setup: NO_MODE_CHAT,
  },
  {
    name: "add-context: empty pick",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { conversation_ids: [] },
  },
  {
    name: "add-context: foreign project_id",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { select_all: true, project_id: projects.p3 },
  },
  {
    name: "add-context: observer refused",
    as: "rita",
    method: "POST",
    path: C(chat.p2, "/add-context"),
    body: { select_all: true },
    setup: [P2_OPEN, P2_CHAT],
  },
  {
    name: "add-context: anonymous",
    as: "anonymous",
    method: "POST",
    path: C(chats.p1, "/add-context"),
    body: { select_all: true },
  },

  // ── POST delete-context ───────────────────────────────────────────
  {
    name: "delete-context: detach",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/delete-context"),
    body: { conversation_id: c1 },
  },
  {
    name: "delete-context: not in the chat",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/delete-context"),
    body: { conversation_id: c2 },
  },
  {
    name: "delete-context: locked",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/delete-context"),
    body: { conversation_id: c1 },
    setup: C1_LOCKED,
  },
  {
    name: "delete-context: missing body field",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/delete-context"),
    body: {},
  },
  {
    name: "delete-context: other tenant",
    as: "bob",
    method: "POST",
    path: C(chats.p1, "/delete-context"),
    body: { conversation_id: c1 },
  },

  // ── POST lock-conversations ───────────────────────────────────────
  {
    name: "lock: marks added conversations",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/lock-conversations"),
  },
  {
    name: "lock: nothing new",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/lock-conversations"),
    setup: C1_LOCKED,
  },
  {
    name: "lock: empty chat",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/lock-conversations"),
    setup: NO_MODE_CHAT,
  },
  {
    name: "lock: other tenant",
    as: "bob",
    method: "POST",
    path: C(chats.p1, "/lock-conversations"),
  },

  // ── GET suggestions ───────────────────────────────────────────────
  {
    name: "suggestions: generated",
    as: "alice",
    method: "GET",
    path: C(chats.p1, "/suggestions"),
    query: { language: "nl" },
    ignoreFields: ["suggestions"],
  },
  {
    name: "suggestions: no mode yet",
    as: "alice",
    method: "GET",
    path: C(chat.noMode, "/suggestions"),
    setup: NO_MODE_CHAT,
  },
  {
    name: "suggestions: other tenant",
    as: "bob",
    method: "GET",
    path: C(chats.p1, "/suggestions"),
  },
  {
    name: "suggestions: anonymous",
    as: "anonymous",
    method: "GET",
    path: C(chats.p1, "/suggestions"),
  },

  // ── POST initialize-mode ──────────────────────────────────────────
  {
    name: "mode: already set",
    as: "alice",
    method: "POST",
    path: C(chats.p1, "/initialize-mode"),
    body: { mode: "overview", project_id: p1 },
  },
  {
    name: "mode: deep dive",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/initialize-mode"),
    body: { mode: "deep_dive", project_id: p1 },
    setup: NO_MODE_CHAT,
    differs: UPDATER,
  },
  {
    name: "mode: agentic",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/initialize-mode"),
    body: { mode: "agentic", project_id: p1 },
    setup: NO_MODE_CHAT,
    differs: UPDATER,
  },
  {
    name: "mode: overview summarises what is missing",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/initialize-mode"),
    body: { mode: "overview", project_id: p1 },
    setup: NO_MODE_CHAT,
    ignoreFields: ["summary"],
    differs: UPDATER,
  },
  {
    name: "mode: unknown mode",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/initialize-mode"),
    body: { mode: "chaos", project_id: p1 },
    setup: NO_MODE_CHAT,
  },
  {
    name: "mode: foreign project",
    as: "alice",
    method: "POST",
    path: C(chat.noMode, "/initialize-mode"),
    body: { mode: "deep_dive", project_id: projects.p3 },
    setup: NO_MODE_CHAT,
  },
  {
    name: "mode: other tenant",
    as: "bob",
    method: "POST",
    path: C(chats.p1, "/initialize-mode"),
    body: { mode: "deep_dive", project_id: p1 },
  },

  // ── POST /api/chats/{id} (the reply stream) ───────────────────────
  // A successful reply streams model text, which cannot match between runs; the stream,
  // its protocols and its failure cleanup are proven on a fake model in packages/chats/test.
  {
    name: "reply: agentic chats use the agentic API",
    as: "alice",
    method: "POST",
    path: C(chat.agentic),
    body: { messages: [{ role: "user", content: "hi" }] },
    setup: AGENTIC_CHAT,
  },
  {
    name: "reply: free tier turn cap",
    as: "bob",
    method: "POST",
    path: C(chat.p3),
    body: { messages: [{ role: "user", content: "four" }] },
    setup: P3_THREE_TURNS,
  },
  {
    name: "reply: bad role",
    as: "alice",
    method: "POST",
    path: C(chats.p1),
    body: { messages: [{ role: "system", content: "x" }] },
  },
  { name: "reply: no body", as: "alice", method: "POST", path: C(chats.p1) },
  {
    name: "reply: observer refused",
    as: "rita",
    method: "POST",
    path: C(chat.p2),
    body: { messages: [{ role: "user", content: "hi" }] },
    setup: [P2_OPEN, P2_CHAT],
  },
  {
    name: "reply: other tenant",
    as: "bob",
    method: "POST",
    path: C(chats.p1),
    body: { messages: [{ role: "user", content: "hi" }] },
  },
  {
    name: "reply: anonymous",
    as: "anonymous",
    method: "POST",
    path: C(chats.p1),
    body: { messages: [{ role: "user", content: "hi" }] },
  },
]);
