import { chats, projects, workspaces } from "../fixtures";
import {
  extra,
  P2_OPEN,
  PRIVATE_METHODOLOGY,
  PUBLIC_METHODOLOGY,
  SEEDED_METHODOLOGY,
  WORKSPACE_METHODOLOGY,
} from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p1, p2, legacy } = projects;
const goal = (p: string) => `/api/v2/bff/projects/${p}/goal`;
const M = "/api/v2/bff/methodologies";
const m = `${M}/${extra.methodology}`;

export default scenarios([
  // ── project goal ──────────────────────────────────────────────────
  { name: "goals get: none yet", as: "alice", method: "GET", path: goal(p1) },
  { name: "goals get: observer", as: "rita", method: "GET", path: goal(p2), setup: [P2_OPEN] },
  { name: "goals get: other tenant", as: "bob", method: "GET", path: goal(p1) },
  { name: "goals get: not onboarded", as: "dave", method: "GET", path: goal(legacy) },
  {
    name: "goals set: owner",
    as: "alice",
    method: "POST",
    path: goal(p1),
    body: { content: "  Hear every street  " },
  },
  {
    name: "goals set: from an interview in a chat",
    as: "admin",
    method: "POST",
    path: goal(p1),
    body: { content: "Map the bus gaps", set_by: "interview", chat_id: chats.p1 },
  },
  {
    name: "goals set: blank",
    as: "alice",
    method: "POST",
    path: goal(p1),
    body: { content: "   " },
  },
  { name: "goals set: empty", as: "alice", method: "POST", path: goal(p1), body: { content: "" } },
  {
    name: "goals set: set_by is fixed",
    as: "alice",
    method: "POST",
    path: goal(p1),
    body: { content: "x", set_by: "loop" },
  },
  {
    name: "goals set: observer refused",
    as: "rita",
    method: "POST",
    path: goal(p2),
    body: { content: "x" },
    setup: [P2_OPEN],
  },
  {
    name: "goals set: other tenant",
    as: "bob",
    method: "POST",
    path: goal(p1),
    body: { content: "x" },
  },
  {
    name: "goals set: chat of nothing",
    as: "alice",
    method: "POST",
    path: goal(p1),
    body: { content: "x", chat_id: "not-a-chat" },
    differs: "L-6: a goal's chat must be a chat of this project",
  },

  // ── methodologies ─────────────────────────────────────────────────
  {
    name: "methodologies list: none",
    as: "alice",
    method: "GET",
    path: M,
    query: { workspace_id: workspaces.aDefault },
  },
  {
    name: "methodologies list: public and workspace ones",
    as: "alice",
    method: "GET",
    path: M,
    query: { workspace_id: workspaces.aDefault },
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies list: public for everyone",
    as: "bob",
    method: "GET",
    path: M,
    query: { workspace_id: workspaces.bDefault },
    setup: PUBLIC_METHODOLOGY,
  },
  {
    name: "methodologies list: no access",
    as: "bob",
    method: "GET",
    path: M,
    query: { workspace_id: workspaces.aDefault },
  },
  {
    name: "methodologies list: missing workspace",
    as: "alice",
    method: "GET",
    path: M,
    query: { workspace_id: extra.project },
  },
  { name: "methodologies list: workspace required", as: "alice", method: "GET", path: M },
  {
    name: "methodologies list: not onboarded",
    as: "dave",
    method: "GET",
    path: M,
    query: { workspace_id: workspaces.aDefault },
  },
  {
    name: "methodologies create: member",
    as: "admin",
    method: "POST",
    path: M,
    body: {
      workspace_id: ` ${workspaces.aDefault} `,
      name: " Citizens panel ",
      description: "Panel",
      framing: "Frame",
      content: { steps: ["a"] },
    },
  },
  {
    name: "methodologies create: no content",
    as: "alice",
    method: "POST",
    path: M,
    body: { workspace_id: workspaces.aDefault, name: "A", description: "B", framing: "C" },
  },
  {
    name: "methodologies create: blank name",
    as: "alice",
    method: "POST",
    path: M,
    body: { workspace_id: workspaces.aDefault, name: "  ", description: "B", framing: "C" },
  },
  {
    name: "methodologies create: validation",
    as: "alice",
    method: "POST",
    path: M,
    body: { workspace_id: "", name: "A" },
  },
  {
    name: "methodologies create: observer refused",
    as: "rita",
    method: "POST",
    path: M,
    body: { workspace_id: workspaces.aResearch, name: "A", description: "B", framing: "C" },
  },
  {
    name: "methodologies create: no access",
    as: "bob",
    method: "POST",
    path: M,
    body: { workspace_id: workspaces.aDefault, name: "A", description: "B", framing: "C" },
  },
  {
    name: "methodologies get: public",
    as: "bob",
    method: "GET",
    path: m,
    setup: PUBLIC_METHODOLOGY,
  },
  {
    name: "methodologies get: shared with the workspace",
    as: "admin",
    method: "GET",
    path: m,
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies get: owner's private one",
    as: "erin",
    method: "GET",
    path: m,
    setup: PRIVATE_METHODOLOGY,
  },
  { name: "methodologies get: missing", as: "alice", method: "GET", path: m },
  {
    name: "methodologies get: outside the workspace",
    as: "bob",
    method: "GET",
    path: m,
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies get: someone else's private one",
    as: "alice",
    method: "GET",
    path: m,
    setup: PRIVATE_METHODOLOGY,
    differs: "L-7: a private methodology is its owner's, not the workspace's",
  },
  {
    name: "methodologies edit: owner, card and new version",
    as: "erin",
    method: "POST",
    path: `${m}/versions`,
    body: { name: " Deliberation v2 ", content: { steps: 4 }, note: " Tightened " },
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies edit: workspace owner",
    as: "alice",
    method: "POST",
    path: `${m}/versions`,
    body: { description: "Shorter" },
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies edit: blank name",
    as: "erin",
    method: "POST",
    path: `${m}/versions`,
    body: { name: " " },
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies edit: member refused",
    as: "admin",
    method: "POST",
    path: `${m}/versions`,
    body: { name: "x" },
    setup: WORKSPACE_METHODOLOGY,
  },
  {
    name: "methodologies edit: seeded is read-only",
    as: "admin",
    method: "POST",
    path: `${m}/versions`,
    body: { name: "x" },
    setup: SEEDED_METHODOLOGY,
  },
  {
    name: "methodologies edit: public, not the owner",
    as: "alice",
    method: "POST",
    path: `${m}/versions`,
    body: { name: "x" },
    setup: PUBLIC_METHODOLOGY,
  },
  {
    name: "methodologies edit: missing",
    as: "alice",
    method: "POST",
    path: `${m}/versions`,
    body: {},
  },
]);
