import { billing, id, orgs, users, workspaces } from "../fixtures";
import { scenarios } from "../runner/scenario";

// Staff console. "admin" is the Directus Administrator, who holds every named staff
// permission; alice is an org owner and still has none. The staff audit rows the new
// side writes are asserted in packages/staff/test, not here.
const ADM = "/api/v2/admin";
const ACC_A = `${ADM}/billing-accounts/${billing.a}`;
const ACC_MISSING = `${ADM}/billing-accounts/ba000000-0000-4000-8000-000000000099`;
const WS = `${ADM}/workspaces/${workspaces.aDefault}`;
const WS_MISSING = `${ADM}/workspaces/c0000000-0000-4000-8000-000000000099`;
const mem = (n: number) => id("e1", n);

export default scenarios([
  // Rollups.
  {
    name: "staff rollup: staff reads this month",
    as: "admin",
    method: "GET",
    path: `${ADM}/billing-rollup`,
  },
  {
    name: "staff rollup: staff reads last month",
    as: "admin",
    method: "GET",
    path: `${ADM}/billing-rollup`,
    query: { month_offset: "-1" },
  },
  {
    name: "staff rollup: a future month is refused",
    as: "admin",
    method: "GET",
    path: `${ADM}/billing-rollup`,
    query: { month_offset: "1" },
  },
  {
    name: "staff rollup: an org owner is not staff",
    as: "alice",
    method: "GET",
    path: `${ADM}/billing-rollup`,
  },
  {
    name: "staff rollup: dave is not staff",
    as: "dave",
    method: "GET",
    path: `${ADM}/billing-rollup`,
  },
  {
    name: "staff rollup: anonymous is refused",
    as: "anonymous",
    method: "GET",
    path: `${ADM}/billing-rollup`,
  },
  {
    name: "staff at-risk: staff reads the list",
    as: "admin",
    method: "GET",
    path: `${ADM}/at-risk`,
  },
  {
    name: "staff at-risk: non-staff is refused",
    as: "erin",
    method: "GET",
    path: `${ADM}/at-risk`,
  },
  {
    name: "staff referral ledger: staff reads it",
    as: "admin",
    method: "GET",
    path: `${ADM}/referral-ledger`,
  },
  {
    name: "staff referral ledger: non-staff is refused",
    as: "alice",
    method: "GET",
    path: `${ADM}/referral-ledger`,
  },
  {
    name: "staff external-led orgs: staff reads them",
    as: "admin",
    method: "GET",
    path: `${ADM}/external-led-orgs`,
  },
  {
    name: "staff external-led orgs: non-staff is refused",
    as: "bob",
    method: "GET",
    path: `${ADM}/external-led-orgs`,
  },
  {
    name: "staff payments: staff reads without Mollie",
    as: "admin",
    method: "GET",
    path: `${ADM}/payments`,
  },
  {
    name: "staff payments: per_account 0 is refused",
    as: "admin",
    method: "GET",
    path: `${ADM}/payments`,
    query: { per_account: "0" },
  },
  {
    name: "staff payments: non-staff is refused",
    as: "alice",
    method: "GET",
    path: `${ADM}/payments`,
  },

  // Discounts.
  {
    name: "staff discount: workspace discount lands on its billing account",
    as: "admin",
    method: "PATCH",
    path: `${WS}/discount`,
    body: { percent_discount: 10 },
    differs:
      "the workspace has no discount columns, so the old write failed; the discount now lands on the workspace's billing account",
  },
  {
    name: "staff discount: nothing to update on a workspace",
    as: "admin",
    method: "PATCH",
    path: `${WS}/discount`,
    body: {},
  },
  {
    name: "staff discount: unknown workspace",
    as: "admin",
    method: "PATCH",
    path: `${WS_MISSING}/discount`,
    body: { percent_discount: 10 },
  },
  {
    name: "staff discount: non-staff is refused on a workspace",
    as: "alice",
    method: "PATCH",
    path: `${WS}/discount`,
    body: { percent_discount: 10 },
  },
  {
    name: "staff discount: staff sets an account discount",
    as: "admin",
    method: "PATCH",
    path: `${ACC_A}/discount`,
    body: { type_discount: "scholarship", percent_discount: 15 },
  },
  {
    name: "staff discount: staff clears both discount fields",
    as: "admin",
    method: "PATCH",
    path: `${ACC_A}/discount`,
    body: { clear_type_discount: true, clear_percent_discount: true, percent_discount: 30 },
  },
  {
    name: "staff discount: nothing to update on an account",
    as: "admin",
    method: "PATCH",
    path: `${ACC_A}/discount`,
    body: {},
  },
  {
    name: "staff discount: above 100 percent is a 422",
    as: "admin",
    method: "PATCH",
    path: `${ACC_A}/discount`,
    body: { percent_discount: 101, type_discount: "friends" },
  },
  {
    name: "staff discount: unknown account",
    as: "admin",
    method: "PATCH",
    path: `${ACC_MISSING}/discount`,
    body: { percent_discount: 5 },
  },
  {
    name: "staff discount: non-staff is refused on an account",
    as: "alice",
    method: "PATCH",
    path: `${ACC_A}/discount`,
    body: { percent_discount: 5 },
  },

  // Partner flag and trials.
  {
    name: "staff partner: staff marks org A as partner",
    as: "admin",
    method: "PATCH",
    path: `${ADM}/orgs/${orgs.a}/partner`,
    body: { is_partner: true },
  },
  {
    name: "staff partner: unknown org",
    as: "admin",
    method: "PATCH",
    path: `${ADM}/orgs/b0000000-0000-4000-8000-000000000099/partner`,
    body: { is_partner: true },
  },
  {
    name: "staff partner: the flag is required",
    as: "admin",
    method: "PATCH",
    path: `${ADM}/orgs/${orgs.a}/partner`,
    body: {},
  },
  {
    name: "staff partner: non-staff is refused",
    as: "alice",
    method: "PATCH",
    path: `${ADM}/orgs/${orgs.a}/partner`,
    body: { is_partner: true },
  },
  {
    name: "staff trial: default changemaker for a month",
    as: "admin",
    method: "POST",
    path: `${ADM}/billing-accounts/${billing.b}/grant-trial`,
    body: {},
  },
  {
    name: "staff trial: a year of guardian",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/grant-trial`,
    body: { tier: "guardian", months: 12 },
  },
  {
    name: "staff trial: thirteen months is refused",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/grant-trial`,
    body: { months: 13 },
  },
  {
    name: "staff trial: unknown account",
    as: "admin",
    method: "POST",
    path: `${ACC_MISSING}/grant-trial`,
    body: {},
  },
  {
    name: "staff trial: non-staff is refused",
    as: "bob",
    method: "POST",
    path: `${ACC_A}/grant-trial`,
    body: {},
  },

  // Workspace controls.
  {
    name: "staff members: staff lists the research workspace",
    as: "admin",
    method: "GET",
    path: `${ADM}/workspaces/${workspaces.aResearch}/members`,
  },
  {
    name: "staff members: an unknown workspace lists nothing",
    as: "admin",
    method: "GET",
    path: `${WS_MISSING}/members`,
  },
  {
    name: "staff members: non-staff is refused",
    as: "alice",
    method: "GET",
    path: `${WS}/members`,
  },
  {
    name: "staff change admin: promotes a member",
    as: "admin",
    method: "POST",
    path: `${WS}/change-admin`,
    body: { membership_id: mem(3) },
  },
  {
    name: "staff change admin: an owner stays owner",
    as: "admin",
    method: "POST",
    path: `${WS}/change-admin`,
    body: { membership_id: mem(1) },
  },
  {
    name: "staff change admin: an external collaborator cannot be promoted",
    as: "admin",
    method: "POST",
    path: `${ADM}/workspaces/${workspaces.aResearch}/change-admin`,
    body: { membership_id: mem(6) },
  },
  {
    name: "staff change admin: a membership of another workspace",
    as: "admin",
    method: "POST",
    path: `${WS}/change-admin`,
    body: { membership_id: mem(4) },
  },
  {
    name: "staff change admin: unknown workspace",
    as: "admin",
    method: "POST",
    path: `${WS_MISSING}/change-admin`,
    body: { membership_id: mem(3) },
  },
  {
    name: "staff change admin: the membership is required",
    as: "admin",
    method: "POST",
    path: `${WS}/change-admin`,
    body: {},
  },
  {
    name: "staff change admin: non-staff is refused",
    as: "alice",
    method: "POST",
    path: `${WS}/change-admin`,
    body: { membership_id: mem(3) },
  },
  {
    name: "staff reset usage: stamps the floor and the reason",
    as: "admin",
    method: "POST",
    path: `${WS}/reset-usage`,
    body: { reason: "Duplicate upload" },
  },
  {
    name: "staff reset usage: an empty reason is refused",
    as: "admin",
    method: "POST",
    path: `${WS}/reset-usage`,
    body: { reason: "" },
  },
  {
    name: "staff reset usage: unknown workspace",
    as: "admin",
    method: "POST",
    path: `${WS_MISSING}/reset-usage`,
    body: { reason: "x" },
  },
  {
    name: "staff reset usage: non-staff is refused",
    as: "erin",
    method: "POST",
    path: `${WS}/reset-usage`,
    body: { reason: "x" },
  },

  // Support access.
  {
    name: "staff support: joining needs the customer's toggle",
    as: "admin",
    method: "POST",
    path: `${WS}/join-support`,
  },
  {
    name: "staff support: joining an unknown workspace",
    as: "admin",
    method: "POST",
    path: `${WS_MISSING}/join-support`,
  },
  {
    name: "staff support: non-staff cannot join",
    as: "alice",
    method: "POST",
    path: `${WS}/join-support`,
  },
  {
    name: "staff support: no session is active",
    as: "admin",
    method: "GET",
    path: `${WS}/join-support`,
  },
  {
    name: "staff support: leaving without a session",
    as: "admin",
    method: "DELETE",
    path: `${WS}/join-support`,
  },
  {
    name: "staff support: non-staff cannot read sessions",
    as: "alice",
    method: "GET",
    path: `${WS}/join-support`,
  },
  {
    name: "staff support request: staff asks for access with a note",
    as: "admin",
    method: "POST",
    path: `${WS}/support-access/request`,
    body: { message: "  Looking into the export issue  " },
  },
  {
    name: "staff support request: an empty note is stored as none",
    as: "admin",
    method: "POST",
    path: `${WS}/support-access/request`,
    body: {},
  },
  {
    name: "staff support request: the body is required",
    as: "admin",
    method: "POST",
    path: `${WS}/support-access/request`,
  },
  {
    name: "staff support request: unknown workspace",
    as: "admin",
    method: "POST",
    path: `${WS_MISSING}/support-access/request`,
    body: {},
  },
  {
    name: "staff support request: non-staff cannot ask",
    as: "alice",
    method: "POST",
    path: `${WS}/support-access/request`,
    body: {},
  },
  {
    name: "staff support request: none pending",
    as: "admin",
    method: "GET",
    path: `${WS}/support-access/request`,
  },
  {
    name: "staff support request: withdrawing nothing",
    as: "admin",
    method: "DELETE",
    path: `${WS}/support-access/request`,
  },
  {
    name: "staff support request: non-staff cannot read requests",
    as: "bob",
    method: "GET",
    path: `${WS}/support-access/request`,
  },

  // Managed billing.
  {
    name: "staff managed: set account A managed with seats",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/set-managed`,
    body: { tier: "changemaker", seats: 3 },
  },
  {
    name: "staff managed: a legacy tier is refused",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/set-managed`,
    body: { tier: "pilot" },
    differs: "L-17: set-managed accepted any tier string; only real tiers are accepted now",
  },
  {
    name: "staff managed: the manager must be dembrane staff",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/set-managed`,
    body: { tier: "changemaker", account_manager_id: users.alice.app },
  },
  {
    name: "staff managed: the tier is required",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/set-managed`,
    body: {},
  },
  {
    name: "staff managed: non-staff is refused",
    as: "alice",
    method: "POST",
    path: `${ACC_A}/set-managed`,
    body: { tier: "free" },
  },
  {
    name: "staff saas: an unmanaged account cannot move to self-serve",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/set-saas`,
    body: { to_free: true },
  },
  {
    name: "staff saas: to_free is required",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/set-saas`,
    body: {},
  },
  {
    name: "staff account manager: an example.com user is refused",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/account-manager`,
    body: { account_manager_id: users.admin.app },
  },
  {
    name: "staff account manager: an unknown user is refused",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/account-manager`,
    body: { account_manager_id: "a0000000-0000-4000-8000-000000000099" },
  },
  {
    name: "staff account manager: staff clears it",
    as: "admin",
    method: "DELETE",
    path: `${ACC_A}/account-manager`,
  },
  {
    name: "staff account manager: unknown account",
    as: "admin",
    method: "DELETE",
    path: `${ACC_MISSING}/account-manager`,
  },
  {
    name: "staff account manager: non-staff cannot clear",
    as: "alice",
    method: "DELETE",
    path: `${ACC_A}/account-manager`,
  },
  {
    name: "staff payment link: without Mollie gets a 400",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/issue-payment-link`,
    body: { amount_eur: 120.5 },
  },
  {
    name: "staff payment link: a zero amount is refused",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/issue-payment-link`,
    body: { amount_eur: 0 },
  },
  {
    name: "staff invoice: without Mollie gets a 400",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/issue-invoice`,
    body: { seats: 3 },
  },
  {
    name: "staff invoice: non-staff is refused",
    as: "alice",
    method: "POST",
    path: `${ACC_A}/issue-invoice`,
    body: {},
  },
  {
    name: "staff invoice paid: without Mollie gets a 400",
    as: "admin",
    method: "POST",
    path: `${ACC_A}/mark-invoice-paid`,
    body: { amount_eur: 300, payment_reference: "PO-1" },
  },
  {
    name: "staff invoice paid: unknown account",
    as: "admin",
    method: "POST",
    path: `${ACC_MISSING}/mark-invoice-paid`,
    body: {},
  },
]);
