// Copies the Python API's prompt templates this namespace renders into a TypeScript
// module, so the models keep seeing the same text. Rerun after a template changes:
//   bun packages/chats/scripts/generate-prompts.ts
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = new URL("../../../../server/prompt_templates", import.meta.url).pathname;
const out = new URL("../src/prompts/templates.generated.ts", import.meta.url).pathname;
const NAMES = [
  "system_chat",
  "context_conversations",
  "context_project",
  "generate_chat_title",
  "suggestions_system",
  "suggestions_user",
  "generate_conversation_summary",
  "generate_conversation_title",
  "generate_conversation_tag_ids",
];
const files = readdirSync(dir)
  .filter((f) => f.endsWith(".jinja") && NAMES.includes(f.split(".")[0] as string))
  .sort();
const body = files.map(
  (f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(dir, f), "utf8"))},`,
);
writeFileSync(
  out,
  `// Generated by scripts/generate-prompts.ts from echo/server/prompt_templates. Do not edit.\nexport const TEMPLATES: Record<string, string> = {\n${body.join("\n")}\n};\n`,
);
