# Separating validation config from echo, since not needed for normal run or any other module 
import os

from dotenv import load_dotenv

load_dotenv()

HF_TOKEN = os.getenv('HF_TOKEN')
VALIDATION_DATASET_REPO = os.getenv('VALIDATION_DATASET_REPO')

DATA_GENERATOR_LLM_MODEL_NAME = os.getenv('LITELLM_LIGHTRAG_NAME')
DATA_GENERATOR_LLM_MODEL_ENDPOINT = os.getenv('LITELLM_LIGHTRAG_ENDPOINT')
DATA_GENERATOR_LLM_MODEL_APIKEY = os.getenv('LITELLM_LIGHTRAG_APIKEY')
DATA_GENERATOR_LLM_MODEL_API_VERSION = os.getenv('LITELLM_LIGHTRAG_API_VERSION')

DATA_GENERATOR_EMBEDDING_ENDPOINT = os.getenv('LITELLM_LIGHTRAG_DATA_GENERATOR_EMBEDDING_ENDPOINT')
DATA_GENERATOR_EMBEDDING_API_KEY = os.getenv('LITELLM_LIGHTRAG_DATA_GENERATOR_EMBEDDING_API_KEY')
DATA_GENERATOR_EMBEDDING_API_VERSION = os.getenv('LITELLM_LIGHTRAG_DATA_GENERATOR_EMBEDDING_API_VERSION')
DATA_GENERATOR_EMBEDDING_DEPLOYMENT = os.getenv('LITELLM_LIGHTRAG_DATA_GENERATOR_EMBEDDING_DEPLOYMENT')

VALIDATION_LLM_MODEL = os.getenv('VALIDATION_LLM_MODEL')
VALIDATION_LLM_API_BASE = os.getenv('VALIDATION_LLM_API_BASE')
VALIDATION_LLM_API_KEY = os.getenv('VALIDATION_LLM_API_KEY')
VALIDATION_LLM_API_VERSION = os.getenv('VALIDATION_LLM_API_VERSION')

WANDB_API_KEY = os.getenv("WANDB_API_KEY")
WANDB_PROJECT = os.getenv("WANDB_PROJECT","lightrag-evaluation")

validation_bsz = int(os.getenv('VALIDATION_BSZ')) # type: ignore
validation_sample_size = int(os.getenv('VALIDATION_SAMPLE_SIZE')) # type: ignore
