/**
 * Participant Recording Flow Test Suite
 * 
 * This test verifies the complete participant recording flow:
 * 1. Login and create a new project
 * 2. Copy portal link and navigate to participant portal
 * 3. Complete privacy, microphone, and session setup
 * 4. Record for 10 seconds and finish
 * 5. Return to dashboard and verify conversation exists
 * 6. Delete project and logout
 * 
 * NOTE: Uses cy.origin() to handle cross-origin navigation between
 * dashboard.echo-next.dembrane.com and portal.echo-next.dembrane.com
 */

import { loginToApp, logout } from '../../support/functions/login';
import { createProject, deleteProject } from '../../support/functions/project';
import { openSettingsMenu } from '../../support/functions/settings';
import { clickTranscriptTab, navigateToProjectOverview, selectConversation, verifyConversationName } from '../../support/functions/conversation';

describe('Participant Recording Flow', () => {
    let projectId;

    beforeEach(() => {
        // Ignore benign application errors
        cy.on('uncaught:exception', (err, runnable) => {
            if (err.message.includes('Syntax error, unrecognized expression') ||
                err.message.includes('BODY[style=') ||
                err.message.includes('ResizeObserver loop limit exceeded')) {
                return false;
            }
            return true;
        });
        loginToApp();
    });

    it('should complete participant recording flow and verify conversation', () => {
        // 1. Create project and capture ID
        cy.log('Step 1: Creating new project');

        // Define text response constant for verification
        const textResponse = 'This is a 150 character automated response generated by Cypress to test the text submission flow. '.repeat(2).substring(0, 150);

        createProject();

        // Capture project ID
        cy.url().then((url) => {
            const parts = url.split('/');
            const projectIndex = parts.indexOf('projects');
            if (projectIndex !== -1 && parts[projectIndex + 1]) {
                projectId = parts[projectIndex + 1];
                cy.log('Captured Project ID:', projectId);
            }
        });

        // 2. Navigate to participant portal and complete flow using cy.origin()
        cy.log('Step 2: Opening participant portal');
        cy.then(() => {
            const portalBaseUrl = Cypress.env('portalUrl') || 'https://portal.echo-next.dembrane.com';
            const portalUrl = `${portalBaseUrl}/en-US/${projectId}/start`;

            // Explicitly grant microphone permission to the portal origin using Chrome DevTools Protocol
            // This is required because cy.origin() context doesn't inherit permissions or flags properly
            cy.log('Granting microphone permission via CDP');
            cy.wrap(null).then(() => {
                const dashboardUrl = Cypress.env('dashboardUrl') || 'https://dashboard.echo-next.dembrane.com';

                // 1. Grant permissions to origins
                const grantPortal = Cypress.automation('remote:debugger:protocol', {
                    command: 'Browser.grantPermissions',
                    params: {
                        permissions: ['audioCapture'],
                        origin: portalBaseUrl
                    }
                });

                const grantDashboard = Cypress.automation('remote:debugger:protocol', {
                    command: 'Browser.grantPermissions',
                    params: {
                        permissions: ['audioCapture'],
                        origin: dashboardUrl
                    }
                });

                return Promise.all([grantPortal, grantDashboard])
                    .then(() => cy.log('Successfully granted permissions via CDP'))
                    .catch((error) => {
                        cy.log('Failed to grant permission via CDP:', error.message);
                    });
            });

            // Use cy.origin() to handle cross-origin commands
            cy.origin(portalBaseUrl, { args: { portalUrl, projectId, textResponse } }, ({ portalUrl, projectId, textResponse }) => {
                // Setup window:before:load listener to stub permissions
                // This is more reliable than cy.visit options or CDP in cy.origin
                cy.on('window:before:load', (win) => {
                    console.log('STUBBING PERMISSIONS via cy.on(window:before:load)');

                    // Stub navigator.permissions.query
                    if (win.navigator.permissions) {
                        const originalQuery = win.navigator.permissions.query.bind(win.navigator.permissions);
                        win.navigator.permissions.query = (desc) => {
                            if (desc.name === 'microphone') {
                                console.log('Mocking microphone permission: granted');
                                return Promise.resolve({ state: 'granted', onchange: null });
                            }
                            return originalQuery(desc);
                        };
                    }
                });

                // Navigate to portal
                cy.visit(portalUrl);

                // 3. Agree to privacy policy
                cy.log('Step 3: Agreeing to privacy policy');
                cy.get('#checkbox-0', { timeout: 10000 }).check({ force: true });
                cy.wait(500);
                cy.get('button').contains('I understand').should('not.be.disabled').click();
                cy.wait(2000);

                // 4. Microphone check
                cy.log('Step 4: Handling microphone check');

                // Wait for the microphone page to fully load
                cy.wait(3000);

                // Skip microphone check directly as requested
                cy.log('Skipping microphone check via Skip button');
                cy.get('[data-testid="portal-onboarding-mic-skip-button"]')
                    .should('be.visible')
                    .click({ force: true });
                cy.wait(1000);

                // 5. Enter session name
                cy.log('Step 5: Entering session name');
                cy.get('input[placeholder="Group 1, John Doe, etc."]').type('Cypress Test Recording');
                cy.get('button').contains('Next').click();
                cy.wait(2000);

                // 6. Handle Microphone Access Denied Modal if present
                cy.log('Step 6: Handling Access Denied Modal & Text Response');

                // Wait for potential modal
                cy.wait(2000);
                cy.get('body').then(($body) => {
                    if ($body.text().includes('microphone access was denied')) {
                        cy.log('Microphone access denied modal detected - clicking Check microphone access');
                        cy.contains('button', 'Check microphone access').click({ force: true });
                        cy.wait(2000);
                    }
                });

                // 7. Click Text Response Icon
                cy.log('Step 7: Selecting Text Response');
                // Target the button containing the text caption icon
                cy.get('button .tabler-icon-text-caption').click({ force: true });
                cy.wait(1000);

                // 8. Type Response
                cy.log('Step 8: Typing Text Response');
                // Use the textResponse variable defined in the main scope
                cy.get('textarea[placeholder="Type your response here"]').type(textResponse);
                cy.wait(1000);

                // 9. Submit Response (Click Submit then Finish)
                cy.log('Step 9: Clicking Submit and then Finish');

                // 9a. Click Submit (Up arrow icon button)
                // Based on screenshot, there is a Submit button. 
                // Using cy.contains or looking for the button with 'Submit' text/aria-label
                cy.log('Step 9a: Clicking Submit');
                cy.contains('button', 'Submit').click({ force: true });
                cy.wait(2000); // 2s wait as per user description

                // 9b. Click Finish (Check icon button)
                cy.log('Step 9b: Clicking Finish');
                cy.contains('button', 'Finish').click({ force: true });
                cy.wait(1000);

                // 10. Confirm Finish Modal
                cy.log('Step 10: Confirming Finish Modal');
                // Wait for modal to appear
                cy.contains('Finish Conversation').should('be.visible');
                cy.contains('Are you sure you want to finish the conversation?').should('be.visible');
                // Click "Yes" button
                cy.contains('button', 'Yes').click({ force: true });
                cy.wait(2000);
            });
        });

        // 10. Return to dashboard
        cy.log('Step 10: Returning to dashboard');
        cy.then(() => {
            const dashboardBaseUrl = Cypress.env('dashboardUrl') || 'https://dashboard.echo-next.dembrane.com';
            cy.visit(`${dashboardBaseUrl}/en-US/projects/${projectId}/overview`);
        });

        // 11. Verify conversation and transcript
        cy.log('Step 11: Verifying conversation and transcript');
        cy.wait(5000); // Wait for conversation list to update

        // Select the conversation using the helper which handles visibility
        selectConversation('Cypress Test Recording');

        // Verify conversation name
        verifyConversationName('Cypress Test Recording');

        // Wait for transcript processing
        cy.log('Waiting 10 seconds for transcript processing');
        cy.wait(10000);

        // Click Transcript tab
        clickTranscriptTab();

        // Verify transcript text matches exactly
        cy.log('Verifying transcript text matches exact response');
        // Using the same xpath selector logic as in verifyTranscriptText helper
        cy.xpath('//div[contains(@class, "mantine-Paper-root")]//div[contains(@style, "flex")]//div/p[contains(@class, "mantine-Text-root")]')
            .each(($el) => {
                // Determine if this is the transcript paragraph by length or positioning if multiple exist
                if ($el.text().length > 50) {
                    expect($el.text().trim()).to.equal(textResponse.trim());
                }
            });

        // 12. Navigate back and Delete project
        cy.log('Step 12: Navigating back and Deleting project');
        navigateToProjectOverview();

        cy.then(() => {
            deleteProject(projectId);
        });

        // 13. Logout
        cy.log('Step 13: Logging out');
        openSettingsMenu();
        logout();
    });
});
