/**
 * Participant Recording Flow Test Suite
 *
 * Split into single-origin tests so it runs in Chromium/Firefox/WebKit
 * without relying on cy.origin().
 */

import { loginToApp, logout } from '../../support/functions/login';
import { createProject, deleteProject } from '../../support/functions/project';
import { openSettingsMenu } from '../../support/functions/settings';
import { clickTranscriptTab, navigateToProjectOverview, selectConversation, verifyConversationName } from '../../support/functions/conversation';
import {
    agreeToPrivacyPolicy,
    enterSessionName,
    handleMicrophoneAccessDenied,
    skipMicrophoneCheck,
    switchToTextMode,
    typePortalText,
    submitText,
    finishTextMode,
    confirmFinishText
} from '../../support/functions/participant';

describe('Participant Recording Flow', () => {
    let projectId;
    const portalLocale = 'en-US';
    const sessionName = 'Cypress Test Recording';
    const textResponse = 'This is a 150 character automated response generated by Cypress to test the text submission flow. '.repeat(2).substring(0, 150);
    const portalBaseUrl = (Cypress.env('portalUrl') || 'https://portal.echo-next.dembrane.com').replace(/\/$/, '');
    const dashboardBaseUrl = (Cypress.env('dashboardUrl') || 'https://dashboard.echo-next.dembrane.com').replace(/\/$/, '');

    const registerExceptionHandling = () => {
        cy.on('uncaught:exception', (err) => {
            if (err.message.includes('Syntax error, unrecognized expression') ||
                err.message.includes('BODY[style=') ||
                err.message.includes('ResizeObserver loop limit exceeded')) {
                return false;
            }
            return true;
        });
    };

    const resolveProjectId = () => {
        return cy.then(() => {
            if (!projectId) {
                projectId = Cypress.env('participantRecordingProjectId');
            }

            if (projectId) {
                return projectId;
            }

            return cy.readFile('fixtures/createdProjects.json', { log: false }).then((projects) => {
                const lastProject = Array.isArray(projects) ? projects[projects.length - 1] : null;
                if (!lastProject || !lastProject.id) {
                    throw new Error('projectId not found. Ensure the create step completed successfully.');
                }
                projectId = lastProject.id;
                Cypress.env('participantRecordingProjectId', projectId);
                return projectId;
            });
        }).then((id) => {
            expect(id, 'projectId').to.be.a('string').and.not.be.empty;
            return id;
        });
    };

    const captureProjectIdFromUrl = () => {
        cy.url().then((url) => {
            const parts = url.split('/');
            const projectIndex = parts.indexOf('projects');
            if (projectIndex !== -1 && parts[projectIndex + 1]) {
                projectId = parts[projectIndex + 1];
                Cypress.env('participantRecordingProjectId', projectId);
                cy.log('Captured Project ID:', projectId);
            }
        });
    };

    const getPortalUrl = () => `${portalBaseUrl}/${portalLocale}/${projectId}/start`;

    it('Step 1: creates a project for participant recording', () => {
        registerExceptionHandling();
        loginToApp();

        cy.log('Step 1: Creating new project');
        createProject();
        captureProjectIdFromUrl();
        resolveProjectId();
    });

    it('Step 2: submits a participant text response in the portal', () => {
        registerExceptionHandling();

        resolveProjectId().then(() => {
            cy.log('Step 2: Opening participant portal');
            cy.visit(getPortalUrl());
        });

        cy.log('Step 3: Agreeing to privacy policy');
        agreeToPrivacyPolicy();

        cy.log('Step 4: Skipping microphone check');
        skipMicrophoneCheck();

        cy.log('Step 5: Entering session name');
        enterSessionName(sessionName);

        cy.log('Step 6: Handling microphone access modal if present');
        handleMicrophoneAccessDenied();

        cy.log('Step 7: Switching to text response');
        switchToTextMode();
        cy.wait(1000);

        cy.log('Step 8: Typing and submitting text response');
        typePortalText(textResponse);
        submitText();
        cy.wait(2000);

        cy.log('Step 9: Finishing conversation');
        finishTextMode();
        confirmFinishText();
        cy.wait(2000);
    });

    it('should complete participant recording flow and verify conversation', () => {
        registerExceptionHandling();
        loginToApp();

        resolveProjectId().then((id) => {
            cy.log('Step 10: Returning to dashboard');
            cy.visit(`${dashboardBaseUrl}/${portalLocale}/projects/${id}/overview`);
        });

        cy.log('Step 11: Verifying conversation and transcript');
        cy.wait(5000);
        selectConversation(sessionName);
        verifyConversationName(sessionName);

        cy.log('Waiting 10 seconds for transcript processing');
        cy.wait(10000);
        clickTranscriptTab();

        cy.log('Verifying transcript text matches exact response');
        cy.xpath('//div[contains(@class, "mantine-Paper-root")]//div[contains(@style, "flex")]//div/p[contains(@class, "mantine-Text-root")]')
            .each(($el) => {
                if ($el.text().length > 50) {
                    expect($el.text().trim()).to.equal(textResponse.trim());
                }
            });

        cy.log('Step 12: Navigating back and Deleting project');
        navigateToProjectOverview();
        resolveProjectId().then((id) => {
            deleteProject(id);
            Cypress.env('participantRecordingProjectId', null);
        });

        cy.log('Step 13: Logging out');
        openSettingsMenu();
        logout();
    });
});
