import {
  ARGS_READY,
  ASSESSED,
  ana,
  CHECKS,
  LEGACY_RESULT,
  LEGACY_V1,
  QUEUED_RUN,
} from "../analysis-setup";
import { projects } from "../fixtures";
import { P2_OPEN } from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p1, p2, legacy } = projects;
const M = "/api/v2/bff/map";
const rev = (i: number) => ana.revisions[i] as string;

export default scenarios([
  // ── project state ─────────────────────────────────────────────────
  {
    name: "map state: a v2 map",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}`,
    setup: ARGS_READY,
  },
  {
    name: "map state: metadata only",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}`,
    query: { metadata_only: "true" },
    setup: ARGS_READY,
  },
  { name: "map state: no map yet", as: "alice", method: "GET", path: `${M}/projects/${p1}` },
  {
    name: "map state: a v1 result",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}`,
    setup: LEGACY_V1,
  },
  {
    name: "map state: a queued generation is the attempt",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}`,
    setup: [...ARGS_READY, ...QUEUED_RUN],
  },
  {
    name: "map state: revalidation",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}`,
    headers: { "if-none-match": "*" },
    setup: ARGS_READY,
  },
  {
    name: "map state: observer",
    as: "rita",
    method: "GET",
    path: `${M}/projects/${p2}`,
    setup: [P2_OPEN],
  },
  { name: "map state: other tenant", as: "bob", method: "GET", path: `${M}/projects/${p1}` },
  { name: "map state: not onboarded", as: "dave", method: "GET", path: `${M}/projects/${legacy}` },
  { name: "map state: anonymous", as: "anonymous", method: "GET", path: `${M}/projects/${p1}` },

  // ── graph ─────────────────────────────────────────────────────────
  {
    name: "map graph: default selection",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    setup: ARGS_READY,
  },
  {
    name: "map graph: chosen types",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { types: "argument,tension" },
    setup: ARGS_READY,
  },
  {
    name: "map graph: nothing selected",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { types: "" },
    setup: ARGS_READY,
  },
  {
    name: "map graph: over the node budget shows counts only",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { node_limit: "2" },
    setup: ARGS_READY,
  },
  {
    name: "map graph: one producer's output",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { scope: "arguments" },
    setup: ARGS_READY,
  },
  {
    name: "map graph: unknown producer",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { scope: "tensions" },
    setup: ARGS_READY,
  },
  {
    name: "map graph: unknown type",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { types: "argument,poem" },
  },
  {
    name: "map graph: budgets that are not numbers",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { node_limit: "many" },
  },
  {
    name: "map graph: an edge budget too small for the tree",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    query: { node_limit: "10", edge_limit: "3" },
  },
  {
    name: "map graph: a new assessment advances the view",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    setup: [...ARGS_READY, ...ASSESSED],
  },
  {
    name: "map graph: a v1 result not yet imported",
    as: "alice",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    setup: LEGACY_V1,
  },
  { name: "map graph: no map yet", as: "alice", method: "GET", path: `${M}/projects/${p1}/graph` },
  {
    name: "map graph: other tenant",
    as: "bob",
    method: "GET",
    path: `${M}/projects/${p1}/graph`,
    setup: ARGS_READY,
  },

  // ── generation ────────────────────────────────────────────────────
  {
    name: "map generate: first map",
    as: "alice",
    method: "POST",
    path: `${M}/projects/${p1}/generate`,
  },
  {
    name: "map generate: a queued run is joined",
    as: "alice",
    method: "POST",
    path: `${M}/projects/${p1}/generate`,
    setup: [...ARGS_READY, ...QUEUED_RUN],
  },
  {
    name: "map generate: observer",
    as: "rita",
    method: "POST",
    path: `${M}/projects/${p2}/generate`,
    setup: [P2_OPEN],
  },
  {
    name: "map generate: other tenant",
    as: "bob",
    method: "POST",
    path: `${M}/projects/${p1}/generate`,
  },

  // ── live events (a stream never ends, so only refusals compare) ───
  {
    name: "map events: other tenant",
    as: "bob",
    method: "GET",
    path: `${M}/projects/${p1}/events`,
  },
  {
    name: "map events: anonymous",
    as: "anonymous",
    method: "GET",
    path: `${M}/projects/${p1}/events`,
  },

  // ── titles ────────────────────────────────────────────────────────
  {
    name: "map title: a snapshot selection",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.result}/title`,
    body: { node_ids: [rev(0), rev(1), rev(2)] },
    ignoreFields: ["title"],
    setup: ARGS_READY,
  },
  {
    name: "map title: too few objects",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/title`,
    body: { node_ids: [rev(0), rev(1)] },
    setup: ARGS_READY,
  },
  {
    name: "map title: an object the snapshot does not show",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/title`,
    body: { node_ids: [rev(0), rev(1), ana.run] },
    setup: ARGS_READY,
  },
  {
    name: "map title: selection of another snapshot",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.result}/title`,
    body: { node_ids: [rev(0)], snapshot_id: ana.run },
    setup: ARGS_READY,
  },
  {
    name: "map title: v1 arguments",
    as: "alice",
    method: "POST",
    path: `${M}/results/${LEGACY_RESULT}/title`,
    body: {
      node_ids: ["a-00000000000000000001", "a-00000000000000000002", "a-00000000000000000003"],
    },
    ignoreFields: ["title"],
    setup: LEGACY_V1,
  },
  {
    name: "map title: empty selection",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.result}/title`,
    body: { node_ids: [] },
    setup: ARGS_READY,
  },
  {
    name: "map title: unknown result",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.run}/title`,
    body: { node_ids: ["x"] },
  },
  {
    name: "map title: other tenant",
    as: "bob",
    method: "POST",
    path: `${M}/results/${ana.result}/title`,
    body: { node_ids: [rev(0), rev(1), rev(2)] },
    setup: ARGS_READY,
  },

  // ── fact-checks ───────────────────────────────────────────────────
  {
    name: "map fact-checks: snapshot states",
    as: "alice",
    method: "GET",
    path: `${M}/results/${ana.result}/fact-checks`,
    setup: [...ARGS_READY, ...ASSESSED],
  },
  {
    name: "map fact-checks: v1 states",
    as: "alice",
    method: "GET",
    path: `${M}/results/${LEGACY_RESULT}/fact-checks`,
    setup: [...LEGACY_V1, ...CHECKS],
  },
  {
    name: "map fact-check: start on a claim revision",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/fact-checks/${rev(0)}`,
    setup: ARGS_READY,
  },
  {
    name: "map fact-check: a finished check stays without force",
    as: "alice",
    method: "POST",
    path: `${M}/results/${LEGACY_RESULT}/fact-checks/a-00000000000000000001`,
    body: {},
    setup: [...LEGACY_V1, ...CHECKS],
  },
  {
    name: "map fact-check: force a re-check",
    as: "alice",
    method: "POST",
    path: `${M}/results/${LEGACY_RESULT}/fact-checks/a-00000000000000000001`,
    body: { force: true },
    setup: [...LEGACY_V1, ...CHECKS],
  },
  {
    name: "map fact-check: an argument is not a claim",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/fact-checks/${rev(1)}`,
    setup: ARGS_READY,
  },
  {
    name: "map fact-check: not in this map",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/fact-checks/${ana.run}`,
    setup: ARGS_READY,
  },
  {
    name: "map fact-check: body validation",
    as: "alice",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/fact-checks/${rev(0)}`,
    body: { force: "sometimes" },
    setup: ARGS_READY,
  },
  {
    name: "map fact-check: observer",
    as: "rita",
    method: "POST",
    path: `${M}/results/${ana.snapshot}/fact-checks/${rev(0)}`,
    setup: [P2_OPEN, ...ARGS_READY],
  },
  {
    name: "map fact-check: cancel a finished one",
    as: "alice",
    method: "DELETE",
    path: `${M}/results/${LEGACY_RESULT}/fact-checks/a-00000000000000000001`,
    setup: [...LEGACY_V1, ...CHECKS],
  },
  {
    name: "map fact-check: cancel on an unknown map",
    as: "alice",
    method: "DELETE",
    path: `${M}/results/nope/fact-checks/x`,
  },
]);
