import { projects } from "../fixtures";
import { DEMO, pop, RUNS, session, versions } from "../popcorn-setup";
import { P2_OPEN } from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p2, p3 } = projects;
const one = (id: number | string, tail = "") => `/api/v2/bff/popcorn/${id}${tail}`;
const settingsPath = one(pop.report, "/settings");
/** An hour and a half from now, so the deprecated loop route rounds to eight hours on both sides. */
const inNinetyMinutes = () => ({ expires_at: new Date(Date.now() + 90 * 60_000).toISOString() });
const H11 =
  "H-11: making a deck public is sharing; it now needs project:share and report:publish (admin or owner, innovator tier)";
const L8 = "L-8: a deck going public gets a fresh link, so one taken down never comes back";

export default scenarios([
  // ── settings ────────────────────────────────────────────────────────
  {
    name: "popcorn settings: title, tabs, voice, words",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: {
      title: "  Night buses  ",
      client: "Transit",
      tabs: { tensions: false, stakeholders: "yes", other: true },
      voice: { presets: ["decisions"] },
      intro: { subtitle: "  Tonight  " },
      notice: { enabled: false },
      data: { enabled: true },
      show_qr: true,
      public_labels: "names",
    },
    setup: session(),
  },
  {
    name: "popcorn settings: a new language dispatches a translation",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { language: { translate_to: "nl", also: ["de", "nl", "de"] } },
    setup: session(),
  },
  {
    name: "popcorn settings: language on a presentation turns the policy explicit",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { language: { ui: "de" } },
    setup: session({ settings: { presentation: { blocks: ["popcorn"], language_policy: "project" } } }),
  },
  {
    name: "popcorn settings: presentation blocks drive the tabs",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { presentation: { blocks: ["tensions", "map"], opening: "map", hidden_items: ["o1", "o1"] } },
    setup: session(),
  },
  {
    name: "popcorn settings: keeps the present draft",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { title: "Renamed" },
    setup: session({ settings: { _present_draft: { revision: 3, saved_at: "x", settings: { title: "Draft" } } } }),
  },
  {
    name: "popcorn settings: same title writes no rename",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { title: "City session", show_branding: true },
    setup: session(),
  },
  {
    name: "popcorn settings: owner makes it public",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { public: true },
    setup: session(),
    differs: L8,
  },
  {
    name: "popcorn settings: already public keeps its link",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { public: true, show_qr: true },
    setup: session({ settings: { public: true } }),
  },
  {
    name: "popcorn settings: public mints a missing token",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { public: true },
    setup: session({ token: null, settings: { public: true } }),
    ignoreFields: ["public_token"],
  },
  {
    name: "popcorn settings: member makes it public",
    as: "admin",
    method: "PATCH",
    path: settingsPath,
    body: { public: true },
    setup: session(),
    differs: H11,
  },
  {
    name: "popcorn settings: external makes it public",
    as: "bob",
    method: "PATCH",
    path: settingsPath,
    body: { public: true },
    setup: [P2_OPEN, ...session({ project: p2 })],
    differs: H11,
  },
  {
    name: "popcorn settings: taking it down",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { public: false },
    setup: session({ settings: { public: true } }),
  },
  {
    name: "popcorn settings: free tier keeps the mark",
    as: "bob",
    method: "PATCH",
    path: settingsPath,
    body: { show_branding: false },
    setup: session({ project: p3, owner: "d0000000-0000-4000-8000-000000000003" }),
  },
  {
    name: "popcorn settings: changemaker drops the mark",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { show_branding: false },
    setup: session(),
  },
  {
    name: "popcorn settings: a demo's frame is locked",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { disclosure: { enabled: true, text: "mine" } },
    setup: session({ state: { demo: DEMO } }),
  },
  {
    name: "popcorn settings: a demo's other words are not",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { intro: { title: "Hi" } },
    setup: session({ state: { demo: DEMO } }),
  },
  {
    name: "popcorn settings: observer",
    as: "rita",
    method: "PATCH",
    path: settingsPath,
    body: { title: "x" },
    setup: [P2_OPEN, ...session({ project: p2 })],
  },
  {
    name: "popcorn settings: invalid",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: {
      presentation: { blocks: ["x", "y", "z", "w", "v"] },
      title: "",
      tabs: { a: "maybe" },
      public_labels: "x",
      voice: { presets: "x" },
      language: { ui: "xx", translate_to: "zz", also: ["en", "xx"] },
    },
    setup: session(),
  },
  { name: "popcorn settings: no body", as: "alice", method: "PATCH", path: settingsPath, setup: session() },
  {
    name: "popcorn settings: a language without its loop",
    as: "alice",
    method: "PATCH",
    path: settingsPath,
    body: { language: { translate_to: "de" } },
    setup: session({ loop: null }),
  },

  // ── read now, rerun, live ───────────────────────────────────────────
  { name: "popcorn refresh: owner", as: "alice", method: "POST", path: one(pop.report, "/refresh"), setup: session() },
  {
    name: "popcorn refresh: observer",
    as: "rita",
    method: "POST",
    path: one(pop.report, "/refresh"),
    setup: [P2_OPEN, ...session({ project: p2 })],
  },
  { name: "popcorn refresh: no loop", as: "alice", method: "POST", path: one(pop.report, "/refresh"), setup: session({ loop: null }) },
  { name: "popcorn rerun: owner", as: "alice", method: "POST", path: one(pop.report, "/rerun"), setup: session() },
  { name: "popcorn rerun: anonymous", as: "anonymous", method: "POST", path: one(pop.report, "/rerun"), setup: session() },
  { name: "popcorn live: eight hours", as: "alice", method: "POST", path: one(pop.report, "/live"), body: { hours: 8 }, setup: session() },
  { name: "popcorn live: five hours", as: "alice", method: "POST", path: one(pop.report, "/live"), body: { hours: 5 }, setup: session() },
  { name: "popcorn live: not a number", as: "alice", method: "POST", path: one(pop.report, "/live"), body: { hours: "x" }, setup: session() },
  { name: "popcorn live: no loop", as: "alice", method: "POST", path: one(pop.report, "/live"), body: { hours: 1 }, setup: session({ loop: null }) },
  {
    name: "popcorn live stop: cancels the booked reads",
    as: "alice",
    method: "POST",
    path: one(pop.report, "/live/stop"),
    setup: [...session({ status: "active" }), ...RUNS],
  },
  { name: "popcorn loop: go-live", as: "alice", method: "POST", path: one(pop.report, "/loop/go-live"), setup: session() },
  { name: "popcorn loop: pause", as: "alice", method: "POST", path: one(pop.report, "/loop/pause"), setup: session({ status: "active" }) },
  { name: "popcorn loop: unknown action", as: "alice", method: "POST", path: one(pop.report, "/loop/jump"), setup: session() },
  { name: "popcorn loop: unknown action, anonymous", as: "anonymous", method: "POST", path: one(pop.report, "/loop/jump") },
  {
    name: "popcorn loop settings: rounds up to a duration",
    as: "alice",
    method: "PATCH",
    path: one(pop.report, "/loop"),
    body: inNinetyMinutes,
    setup: session(),
  },
  { name: "popcorn loop settings: missing expiry", as: "alice", method: "PATCH", path: one(pop.report, "/loop"), body: {}, setup: session() },

  // ── saved runs ──────────────────────────────────────────────────────
  { name: "popcorn versions: newest first", as: "alice", method: "GET", path: one(pop.report, "/versions"), setup: [...session(), ...versions()] },
  { name: "popcorn versions: none", as: "alice", method: "GET", path: one(pop.report, "/versions"), setup: session() },
  { name: "popcorn versions: other tenant", as: "bob", method: "GET", path: one(pop.report, "/versions"), setup: session() },
]);
