import { projects } from "../fixtures";
import {
  METRICS,
  NEWER_CONVERSATION,
  OPTED_IN,
  P1_DRAFT,
  P1_FAILED_REPORT,
  P1_SCHEDULED,
  P2_OPEN,
  P2_REPORT,
  P3_REPORT,
} from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p1, p2, p3, legacy } = projects;
const r = (p: string, tail = "") => `/api/projects/${p}${tail}`;

export default scenarios([
  // ── reads ─────────────────────────────────────────────────────────
  { name: "reports list: owner", as: "alice", method: "GET", path: r(p1, "/reports") },
  {
    name: "reports list: with a draft and a scheduled one",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports"),
    setup: [P1_DRAFT],
  },
  {
    name: "reports list: observer",
    as: "rita",
    method: "GET",
    path: r(p2, "/reports"),
    setup: [P2_OPEN, P2_REPORT],
  },
  { name: "reports list: other tenant", as: "bob", method: "GET", path: r(p1, "/reports") },
  { name: "reports list: not onboarded", as: "dave", method: "GET", path: r(legacy, "/reports") },
  { name: "reports list: anonymous", as: "anonymous", method: "GET", path: r(p1, "/reports") },
  {
    name: "reports list: staff without membership",
    as: "admin",
    method: "GET",
    path: r(p3, "/reports"),
    differs: "H-14: no blanket staff access to another tenant's reports",
  },
  { name: "reports latest: owner", as: "alice", method: "GET", path: r(p1, "/reports/latest") },
  { name: "reports latest: none yet", as: "bob", method: "GET", path: r(p3, "/reports/latest") },
  { name: "reports detail: owner", as: "alice", method: "GET", path: r(p1, "/reports/1/detail") },
  {
    name: "reports detail: missing",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/99/detail"),
  },
  {
    name: "reports detail: report of another project",
    as: "bob",
    method: "GET",
    path: r(p3, "/reports/1/detail"),
  },
  {
    name: "reports detail: id must be an integer",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/abc/detail"),
  },
  { name: "reports views: none", as: "alice", method: "GET", path: r(p1, "/reports/1/views") },
  {
    name: "reports views: total and recent",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/1/views"),
    setup: [METRICS],
  },
  {
    name: "reports views: report of another project",
    as: "bob",
    method: "GET",
    path: r(p3, "/reports/1/views"),
    setup: [METRICS],
    differs: "M-11: a report id counts only inside its own project",
  },
  {
    name: "reports needs-update: current",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/1/needs-update"),
  },
  {
    name: "reports needs-update: newer conversation",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/1/needs-update"),
    setup: [NEWER_CONVERSATION],
  },
  {
    name: "reports needs-update: missing",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/99/needs-update"),
  },
  {
    name: "reports needs-update: report of another project",
    as: "bob",
    method: "GET",
    path: r(p3, "/reports/1/needs-update"),
    setup: [NEWER_CONVERSATION],
    differs: "M-11: a report id counts only inside its own project",
  },
  {
    name: "reports participants: none",
    as: "alice",
    method: "GET",
    path: r(p1, "/participants/count"),
  },
  {
    name: "reports participants: opted in only",
    as: "alice",
    method: "GET",
    path: r(p1, "/participants/count"),
    setup: [OPTED_IN],
  },
  {
    name: "reports participants: other tenant",
    as: "bob",
    method: "GET",
    path: r(p1, "/participants/count"),
  },
  {
    name: "reports progress: already published",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/1/progress"),
  },
  {
    name: "reports progress: failed",
    as: "alice",
    method: "GET",
    path: r(p1, "/reports/1/progress"),
    setup: [P1_FAILED_REPORT],
  },
  {
    name: "reports progress: other tenant",
    as: "bob",
    method: "GET",
    path: r(p1, "/reports/1/progress"),
  },

  // ── POST create-report ────────────────────────────────────────────
  {
    name: "reports create: now",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: { language: "nl" },
  },
  {
    name: "reports create: with instructions",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: { user_instructions: "Focus on buses" },
  },
  {
    name: "reports create: one draft at a time",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: {},
    setup: [P1_DRAFT],
  },
  {
    name: "reports create: scheduled",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: { scheduled_at: "2099-01-01T10:00:00Z", user_instructions: "Later" },
  },
  {
    name: "reports create: scheduled beside a draft",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: { scheduled_at: "2099-01-01T10:00:00+02:00" },
    setup: [P1_DRAFT],
  },
  {
    name: "reports create: schedule in the past",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: { scheduled_at: "2020-01-01T10:00:00Z" },
  },
  {
    name: "reports create: schedule unreadable",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
    body: { scheduled_at: "next tuesday" },
  },
  {
    name: "reports create: free tier first report",
    as: "bob",
    method: "POST",
    path: r(p3, "/create-report"),
    body: {},
  },
  {
    name: "reports create: free tier limit",
    as: "bob",
    method: "POST",
    path: r(p3, "/create-report"),
    body: {},
    setup: [P3_REPORT],
  },
  {
    name: "reports create: external generates",
    as: "bob",
    method: "POST",
    path: r(p2, "/create-report"),
    body: {},
    setup: [P2_OPEN],
  },
  {
    name: "reports create: observer refused",
    as: "rita",
    method: "POST",
    path: r(p2, "/create-report"),
    body: {},
    setup: [P2_OPEN],
  },
  {
    name: "reports create: other tenant",
    as: "bob",
    method: "POST",
    path: r(p1, "/create-report"),
    body: {},
  },
  {
    name: "reports create: not onboarded",
    as: "dave",
    method: "POST",
    path: r(legacy, "/create-report"),
    body: {},
  },
  {
    name: "reports create: missing body",
    as: "alice",
    method: "POST",
    path: r(p1, "/create-report"),
  },

  // ── PATCH reports/{rid} ───────────────────────────────────────────
  {
    name: "reports update: content",
    as: "alice",
    method: "PATCH",
    path: r(p1, "/reports/1"),
    body: { content: "# Rewritten", show_portal_link: true },
  },
  {
    name: "reports update: publish archives the others",
    as: "alice",
    method: "PATCH",
    path: r(p1, "/reports/2"),
    body: { status: "published" },
    setup: [P1_DRAFT],
  },
  {
    name: "reports update: reschedule",
    as: "alice",
    method: "PATCH",
    path: r(p1, "/reports/2"),
    body: { scheduled_at: "2099-02-01T10:00:00Z" },
    setup: P1_SCHEDULED,
  },
  {
    name: "reports update: nothing to update",
    as: "alice",
    method: "PATCH",
    path: r(p1, "/reports/1"),
    body: {},
  },
  {
    name: "reports update: schedule in the past",
    as: "alice",
    method: "PATCH",
    path: r(p1, "/reports/1"),
    body: { scheduled_at: "2020-01-01T00:00:00Z" },
  },
  {
    name: "reports update: bad id",
    as: "alice",
    method: "PATCH",
    path: r(p1, "/reports/abc"),
    body: {},
  },
  {
    name: "reports update: external cannot publish",
    as: "bob",
    method: "PATCH",
    path: r(p2, "/reports/2"),
    body: { status: "published" },
    setup: [P2_OPEN, P2_REPORT],
  },
  {
    name: "reports update: report of another tenant",
    as: "bob",
    method: "PATCH",
    path: r(p3, "/reports/1"),
    body: { content: "# Mine now" },
    differs: "C-3: the report must belong to the project in the path",
  },
  {
    name: "reports update: observer cannot edit content",
    as: "rita",
    method: "PATCH",
    path: r(p2, "/reports/2"),
    body: { content: "# Edited" },
    setup: [P2_OPEN, P2_REPORT],
    differs: "M-8: editing a report needs project:update",
  },

  // ── DELETE reports/{rid} and cancel-schedule ──────────────────────
  { name: "reports delete: owner", as: "alice", method: "DELETE", path: r(p1, "/reports/1") },
  {
    name: "reports delete: scheduled cancels its task",
    as: "alice",
    method: "DELETE",
    path: r(p1, "/reports/2"),
    setup: P1_SCHEDULED,
  },
  {
    name: "reports delete: report of another project",
    as: "bob",
    method: "DELETE",
    path: r(p3, "/reports/1"),
  },
  {
    name: "reports delete: member refused",
    as: "admin",
    method: "DELETE",
    path: r(p1, "/reports/1"),
    differs: "H-9: deleting a report needs report:delete (admins)",
  },
  {
    name: "reports cancel: scheduled",
    as: "alice",
    method: "POST",
    path: r(p1, "/reports/2/cancel-schedule"),
    setup: P1_SCHEDULED,
  },
  {
    name: "reports cancel: not scheduled",
    as: "alice",
    method: "POST",
    path: r(p1, "/reports/1/cancel-schedule"),
  },
  {
    name: "reports cancel: report of another project",
    as: "bob",
    method: "POST",
    path: r(p3, "/reports/1/cancel-schedule"),
  },
  {
    name: "reports cancel: observer refused",
    as: "rita",
    method: "POST",
    path: r(p2, "/reports/2/cancel-schedule"),
    setup: [
      P2_OPEN,
      `insert into project_report (project_id, status, language, kind, content, date_created) values ('${p2}', 'scheduled', 'nl', 'report', '', now())`,
    ],
    differs: "H-9: unscheduling needs report:publish",
  },
]);
