import { conversations, projects, tags, workspaces } from "../fixtures";
import { EMPTY_PROJECT, extra, P2_OPEN, P2_TAG, UNTRANSCRIBED } from "../projects-setup";
import { scenarios } from "../runner/scenario";

const { p1, p2, p3, legacy } = projects;
const v1 = (p: string, tail = "") => `/api/projects/${p}${tail}`;
const v2 = (p: string, tail = "") => `/api/v2/projects/${p}${tail}`;
const bff = (p: string) => `/api/v2/bff/projects/${p}`;

export default scenarios([
  // ── PATCH /api/projects/{id}/pin ──────────────────────────────────
  {
    name: "projects pin: owner pins",
    as: "alice",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: 1 },
  },
  {
    name: "projects pin: owner unpins",
    as: "alice",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: null },
  },
  {
    name: "projects pin: member pins",
    as: "admin",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: 2 },
  },
  {
    name: "projects pin: legacy creator pins",
    as: "dave",
    method: "PATCH",
    path: v1(legacy, "/pin"),
    body: { pin_order: 3 },
  },
  {
    name: "projects pin: order out of range",
    as: "alice",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: 5 },
  },
  {
    name: "projects pin: order not an integer",
    as: "alice",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: "x" },
  },
  { name: "projects pin: missing body", as: "alice", method: "PATCH", path: v1(p1, "/pin") },
  {
    name: "projects pin: missing project",
    as: "alice",
    method: "PATCH",
    path: v1(extra.project, "/pin"),
    body: { pin_order: 1 },
  },
  {
    name: "projects pin: anonymous",
    as: "anonymous",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: 1 },
  },
  {
    name: "projects pin: other tenant",
    as: "bob",
    method: "PATCH",
    path: v1(p1, "/pin"),
    body: { pin_order: 1 },
    differs: "M-12: no project access is 404, not 403 'Not a member of this workspace'",
  },
  {
    name: "projects pin: observer refused",
    as: "rita",
    method: "PATCH",
    path: v1(p2, "/pin"),
    body: { pin_order: 1 },
    setup: [P2_OPEN],
    differs: "M-12: pinning needs project:update, refused as 'Not allowed'",
  },
  {
    name: "projects pin: external may pin",
    as: "bob",
    method: "PATCH",
    path: v1(p2, "/pin"),
    body: { pin_order: 1 },
    setup: [P2_OPEN],
    differs: "M-12: externals hold project:update, the Python refused them by role name",
  },

  // ── DELETE /api/projects/{id} ─────────────────────────────────────
  { name: "projects delete v1: owner", as: "alice", method: "DELETE", path: v1(p1) },
  { name: "projects delete v1: other tenant", as: "bob", method: "DELETE", path: v1(p1) },
  { name: "projects delete v1: anonymous", as: "anonymous", method: "DELETE", path: v1(p1) },
  { name: "projects delete v1: not onboarded", as: "dave", method: "DELETE", path: v1(legacy) },
  {
    name: "projects delete v1: member refused",
    as: "admin",
    method: "DELETE",
    path: v1(p1),
    differs: "C-5: deleting needs project:delete (admins), any role could before",
  },
  {
    name: "projects delete v1: staff without membership",
    as: "admin",
    method: "DELETE",
    path: v1(p3),
    differs: "H-14: no blanket staff access; staff reach customer data only through membership",
  },

  // ── DELETE /api/projects/{id}/tags/{tag_id} ───────────────────────
  {
    name: "projects tag delete v1: owner",
    as: "alice",
    method: "DELETE",
    path: v1(p1, `/tags/${tags.p1Energy}`),
  },
  {
    name: "projects tag delete v1: other tenant's project",
    as: "bob",
    method: "DELETE",
    path: v1(p1, `/tags/${tags.p1Energy}`),
  },
  {
    name: "projects tag delete v1: tag of another project",
    as: "bob",
    method: "DELETE",
    path: v1(p3, `/tags/${tags.p1Energy}`),
    differs: "H-3: a tag is deleted only through its own project",
  },
  {
    name: "projects tag delete v1: observer refused",
    as: "rita",
    method: "DELETE",
    path: v1(p2, `/tags/${extra.tag}`),
    setup: [P2_OPEN, P2_TAG],
    differs: "H-3: deleting a tag needs project:update",
  },

  // ── POST /api/projects/{id}/conversations/{cid}/tags/delete ───────
  {
    name: "projects conversation tags delete: owner",
    as: "alice",
    method: "POST",
    path: v1(p1, `/conversations/${conversations.c1}/tags/delete`),
    body: { tag_ids: [1] },
  },
  {
    name: "projects conversation tags delete: ids must be integers",
    as: "alice",
    method: "POST",
    path: v1(p1, `/conversations/${conversations.c1}/tags/delete`),
    body: { tag_ids: ["x"] },
  },
  {
    name: "projects conversation tags delete: other tenant's project",
    as: "bob",
    method: "POST",
    path: v1(p1, `/conversations/${conversations.c1}/tags/delete`),
    body: { tag_ids: [1] },
  },
  {
    name: "projects conversation tags delete: link of another tenant",
    as: "bob",
    method: "POST",
    path: v1(p3, `/conversations/${conversations.c3}/tags/delete`),
    body: { tag_ids: [1] },
    differs: "C-4: only links of this conversation in this project are deleted",
  },

  // ── GET /api/projects/{id}/transcripts ────────────────────────────
  // The zip itself carries file times, so its bytes differ run to run; its names and contents are unit tested.
  {
    name: "projects transcripts: no conversations",
    as: "alice",
    method: "GET",
    path: v1(extra.project, "/transcripts"),
    setup: [EMPTY_PROJECT],
  },
  {
    name: "projects transcripts: nothing transcribed",
    as: "alice",
    method: "GET",
    path: v1(extra.project, "/transcripts"),
    setup: [EMPTY_PROJECT, UNTRANSCRIBED],
  },
  {
    name: "projects transcripts: other tenant",
    as: "bob",
    method: "GET",
    path: v1(p1, "/transcripts"),
  },
  {
    name: "projects transcripts: anonymous",
    as: "anonymous",
    method: "GET",
    path: v1(p1, "/transcripts"),
  },

  // ── The old library, pruned ───────────────────────────────────────
  {
    name: "projects create-library: removed",
    as: "alice",
    method: "POST",
    path: v1(p1, "/create-library"),
    body: { language: "nl" },
    removed:
      "the old library (views, aspects, quotes) had no entry point in the app and no prod traffic",
  },
  {
    name: "projects create-view: removed",
    as: "alice",
    method: "POST",
    path: v1(p1, "/create-view"),
    body: { query: "mobility" },
    removed:
      "the old library (views, aspects, quotes) had no entry point in the app and no prod traffic",
  },
  {
    name: "library views list: removed",
    as: "alice",
    method: "GET",
    path: "/api/v2/bff/views",
    query: { project_id: p1 },
    removed:
      "the old library (views, aspects, quotes) had no entry point in the app and no prod traffic",
  },
  {
    name: "library view get: removed",
    as: "alice",
    method: "GET",
    path: `/api/v2/bff/views/${extra.run}`,
    removed:
      "the old library (views, aspects, quotes) had no entry point in the app and no prod traffic",
  },
  {
    name: "library aspect get: removed",
    as: "alice",
    method: "GET",
    path: `/api/v2/bff/aspects/${extra.run}`,
    removed:
      "the old library (views, aspects, quotes) had no entry point in the app and no prod traffic",
  },
  {
    name: "library quote get: removed",
    as: "alice",
    method: "GET",
    path: `/api/v2/bff/aspect-segments/${extra.run}`,
    removed:
      "the old library (views, aspects, quotes) had no entry point in the app and no prod traffic",
  },

  // ── POST /api/projects/{id}/clone ─────────────────────────────────
  {
    name: "projects clone: owner with a new name",
    as: "alice",
    method: "POST",
    path: v1(p1, "/clone"),
    body: { name: "City listening copy" },
  },
  {
    name: "projects clone: keeps the name",
    as: "erin",
    method: "POST",
    path: v1(p1, "/clone"),
    body: {},
  },
  {
    name: "projects clone: observer refused",
    as: "rita",
    method: "POST",
    path: v1(p2, "/clone"),
    body: {},
    setup: [P2_OPEN],
  },
  {
    name: "projects clone: other tenant",
    as: "bob",
    method: "POST",
    path: v1(p1, "/clone"),
    body: {},
  },
  {
    name: "projects clone: not onboarded",
    as: "dave",
    method: "POST",
    path: v1(legacy, "/clone"),
    body: {},
  },

  // ── GET /api/v2/projects/{id} ─────────────────────────────────────
  { name: "projects v2 detail: owner", as: "alice", method: "GET", path: v2(p1) },
  { name: "projects v2 detail: inherited org admin", as: "erin", method: "GET", path: v2(p1) },
  {
    name: "projects v2 detail: private project, workspace owner",
    as: "erin",
    method: "GET",
    path: v2(p2),
  },
  {
    name: "projects v2 detail: private project, member without share",
    as: "alice",
    method: "GET",
    path: v2(p2),
  },
  {
    name: "projects v2 detail: observer",
    as: "rita",
    method: "GET",
    path: v2(p2),
    setup: [P2_OPEN],
  },
  { name: "projects v2 detail: other tenant", as: "bob", method: "GET", path: v2(p1) },
  { name: "projects v2 detail: not onboarded", as: "dave", method: "GET", path: v2(legacy) },
  { name: "projects v2 detail: bad id", as: "alice", method: "GET", path: v2("not-a-uuid") },
  { name: "projects v2 detail: anonymous", as: "anonymous", method: "GET", path: v2(p1) },

  // ── GET /api/v2/projects/{id}/bff ─────────────────────────────────
  { name: "projects v2 bff: owner, whole row", as: "alice", method: "GET", path: v2(p1, "/bff") },
  {
    name: "projects v2 bff: legal block",
    as: "alice",
    method: "GET",
    path: v2(p1, "/bff"),
    query: { include_legal: "true" },
  },
  {
    name: "projects v2 bff: fields and no tags",
    as: "alice",
    method: "GET",
    path: v2(p1, "/bff"),
    query: { fields: "name, visibility", include_tags: "false" },
  },
  {
    name: "projects v2 bff: bad boolean",
    as: "alice",
    method: "GET",
    path: v2(p1, "/bff"),
    query: { include_tags: "maybe" },
  },
  {
    name: "projects v2 bff: private project owner",
    as: "erin",
    method: "GET",
    path: v2(p2, "/bff"),
    query: { include_legal: "true" },
  },
  { name: "projects v2 bff: other tenant", as: "bob", method: "GET", path: v2(p1, "/bff") },
  { name: "projects v2 bff: not onboarded", as: "dave", method: "GET", path: v2(legacy, "/bff") },

  // ── POST /api/v2/projects/{id}/move and /bulk-move ────────────────
  {
    name: "projects move: admin on both sides",
    as: "erin",
    method: "POST",
    path: v2(p2, "/move"),
    body: { target_workspace_id: workspaces.aDefault },
  },
  {
    name: "projects move: member of the target",
    as: "alice",
    method: "POST",
    path: v2(p1, "/move"),
    body: { target_workspace_id: workspaces.aResearch },
  },
  {
    name: "projects move: no access to the target",
    as: "bob",
    method: "POST",
    path: v2(p3, "/move"),
    body: { target_workspace_id: workspaces.aDefault },
  },
  {
    name: "projects move: no access to the source",
    as: "bob",
    method: "POST",
    path: v2(p1, "/move"),
    body: { target_workspace_id: workspaces.bDefault },
  },
  {
    name: "projects move: across billing contexts",
    as: "alice",
    method: "POST",
    path: v2(p1, "/move"),
    body: { target_workspace_id: workspaces.bDefault },
  },
  {
    name: "projects move: missing target",
    as: "erin",
    method: "POST",
    path: v2(p1, "/move"),
    body: { target_workspace_id: extra.project },
  },
  {
    name: "projects move: target required",
    as: "erin",
    method: "POST",
    path: v2(p1, "/move"),
    body: {},
  },
  {
    name: "projects move: missing project",
    as: "erin",
    method: "POST",
    path: v2(extra.project, "/move"),
    body: { target_workspace_id: workspaces.aDefault },
  },
  {
    name: "projects bulk-move: all or nothing, success",
    as: "erin",
    method: "POST",
    path: "/api/v2/projects/bulk-move",
    body: { project_ids: [p1, p2, p1], target_workspace_id: workspaces.aResearch },
  },
  {
    name: "projects bulk-move: one refused moves none",
    as: "alice",
    method: "POST",
    path: "/api/v2/projects/bulk-move",
    body: { project_ids: [p2, p1], target_workspace_id: workspaces.aDefault },
  },
  {
    name: "projects bulk-move: empty",
    as: "erin",
    method: "POST",
    path: "/api/v2/projects/bulk-move",
    body: { project_ids: [], target_workspace_id: workspaces.aDefault },
  },
  {
    name: "projects bulk-move: missing project",
    as: "erin",
    method: "POST",
    path: "/api/v2/projects/bulk-move",
    body: { project_ids: [p1, extra.project], target_workspace_id: workspaces.aDefault },
  },
  {
    name: "projects bulk-move: bad body",
    as: "erin",
    method: "POST",
    path: "/api/v2/projects/bulk-move",
    body: { project_ids: "x" },
  },

  // ── PATCH /api/v2/projects/{id}/visibility ────────────────────────
  {
    name: "projects visibility: owner makes private, members told",
    as: "alice",
    method: "PATCH",
    path: v2(p1, "/visibility"),
    body: { visibility: "private" },
  },
  {
    name: "projects visibility: unchanged",
    as: "alice",
    method: "PATCH",
    path: v2(p1, "/visibility"),
    body: { visibility: "workspace" },
  },
  {
    name: "projects visibility: back to the workspace",
    as: "erin",
    method: "PATCH",
    path: v2(p2, "/visibility"),
    body: { visibility: "workspace" },
  },
  {
    name: "projects visibility: free tier cannot go private",
    as: "bob",
    method: "PATCH",
    path: v2(p3, "/visibility"),
    body: { visibility: "private" },
  },
  {
    name: "projects visibility: member refused",
    as: "admin",
    method: "PATCH",
    path: v2(p1, "/visibility"),
    body: { visibility: "private" },
  },
  {
    name: "projects visibility: observer refused",
    as: "rita",
    method: "PATCH",
    path: v2(p2, "/visibility"),
    body: { visibility: "workspace" },
  },
  {
    name: "projects visibility: other tenant",
    as: "bob",
    method: "PATCH",
    path: v2(p1, "/visibility"),
    body: { visibility: "private" },
  },
  {
    name: "projects visibility: legacy project",
    as: "alice",
    method: "PATCH",
    path: v2(legacy, "/visibility"),
    body: { visibility: "private" },
  },
  {
    name: "projects visibility: bad value",
    as: "alice",
    method: "PATCH",
    path: v2(p1, "/visibility"),
    body: { visibility: "public" },
  },

  // ── GET /api/v2/projects/{id}/conversation-usage ──────────────────
  {
    name: "projects usage: owner",
    as: "alice",
    method: "GET",
    path: v2(p1, "/conversation-usage"),
  },
  {
    name: "projects usage: with a deleted conversation",
    as: "alice",
    method: "GET",
    path: v2(p1, "/conversation-usage"),
    setup: [`update conversation set deleted_at = now() where id = '${conversations.c1}'`],
  },
  {
    name: "projects usage: observer",
    as: "rita",
    method: "GET",
    path: v2(p2, "/conversation-usage"),
    setup: [P2_OPEN],
  },
  {
    name: "projects usage: other tenant",
    as: "bob",
    method: "GET",
    path: v2(p1, "/conversation-usage"),
  },

  // ── GET /api/v2/bff/projects ──────────────────────────────────────
  { name: "projects bff list: owner", as: "alice", method: "GET", path: "/api/v2/bff/projects" },
  {
    name: "projects bff list: workspace owner sees private",
    as: "erin",
    method: "GET",
    path: "/api/v2/bff/projects",
  },
  { name: "projects bff list: other org", as: "bob", method: "GET", path: "/api/v2/bff/projects" },
  {
    name: "projects bff list: observer",
    as: "rita",
    method: "GET",
    path: "/api/v2/bff/projects",
    setup: [P2_OPEN],
  },
  {
    name: "projects bff list: search, any word order",
    as: "erin",
    method: "GET",
    path: "/api/v2/bff/projects",
    query: { search: "listening city" },
  },
  {
    name: "projects bff list: paging",
    as: "erin",
    method: "GET",
    path: "/api/v2/bff/projects",
    query: { limit: "1", offset: "1" },
  },
  {
    name: "projects bff list: bad paging",
    as: "erin",
    method: "GET",
    path: "/api/v2/bff/projects",
    query: { limit: "0", offset: "-1" },
  },
  {
    name: "projects bff list: not onboarded",
    as: "dave",
    method: "GET",
    path: "/api/v2/bff/projects",
  },

  // ── PATCH /api/v2/bff/projects/{id} ───────────────────────────────
  {
    name: "projects bff update: rename",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { name: "Renamed", host_guide: { steps: 2 }, selected_verification_key_list: null },
  },
  {
    name: "projects bff update: nothing to update",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: {},
  },
  {
    name: "projects bff update: validation",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { is_verify_enabled: "maybe", host_guide: 5, legal_basis: "x" },
  },
  {
    name: "projects bff update: free tier keeps the event invitation",
    as: "bob",
    method: "PATCH",
    path: bff(p3),
    body: { is_dembrane_event_cta_enabled: false },
  },
  {
    name: "projects bff update: paid tier hides the event invitation",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { is_dembrane_event_cta_enabled: false },
  },
  {
    name: "projects bff update: consent needs a link",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { legal_basis: "consent" },
  },
  {
    name: "projects bff update: consent with a link",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { legal_basis: "consent", privacy_policy_url: " https://example.com/privacy " },
  },
  {
    name: "projects bff update: link must be http",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { legal_basis: "consent", privacy_policy_url: "example.com" },
  },
  {
    name: "projects bff update: dembrane-events needs a dembrane account",
    as: "alice",
    method: "PATCH",
    path: bff(p1),
    body: { legal_basis: "dembrane-events" },
  },
  {
    name: "projects bff update: member cannot set the legal basis",
    as: "admin",
    method: "PATCH",
    path: bff(p1),
    body: { legal_basis: "client-managed" },
  },
  {
    name: "projects bff update: member edits",
    as: "admin",
    method: "PATCH",
    path: bff(p1),
    body: { context: "New context" },
  },
  {
    name: "projects bff update: observer refused",
    as: "rita",
    method: "PATCH",
    path: bff(p2),
    body: { name: "x" },
    setup: [P2_OPEN],
  },
  {
    name: "projects bff update: other tenant",
    as: "bob",
    method: "PATCH",
    path: bff(p1),
    body: { name: "x" },
  },

  // ── DELETE /api/v2/bff/projects/{id} ──────────────────────────────
  { name: "projects bff delete: owner", as: "alice", method: "DELETE", path: bff(p1) },
  { name: "projects bff delete: member refused", as: "admin", method: "DELETE", path: bff(p1) },
  { name: "projects bff delete: other tenant", as: "bob", method: "DELETE", path: bff(p1) },
  { name: "projects bff delete: anonymous", as: "anonymous", method: "DELETE", path: bff(p1) },
]);
