import { workspaces } from "../fixtures";
import { extra, TEMPLATES } from "../projects-setup";
import { scenarios } from "../runner/scenario";

const PT = "/api/templates/prompt-templates";
const QA = "/api/templates/quick-access";

export default scenarios([
  // ── prompt templates ──────────────────────────────────────────────
  { name: "templates list: none", as: "alice", method: "GET", path: PT },
  {
    name: "templates list: personal only without a workspace",
    as: "alice",
    method: "GET",
    path: PT,
    setup: TEMPLATES,
  },
  {
    name: "templates list: with the workspace's shared ones",
    as: "alice",
    method: "GET",
    path: PT,
    query: { workspace_id: workspaces.aDefault },
    setup: TEMPLATES,
  },
  {
    name: "templates list: observer reads, cannot edit",
    as: "rita",
    method: "GET",
    path: PT,
    query: { workspace_id: workspaces.aResearch },
    setup: TEMPLATES,
  },
  {
    name: "templates list: outsider gets only their own",
    as: "bob",
    method: "GET",
    path: PT,
    query: { workspace_id: workspaces.aDefault },
    setup: TEMPLATES,
  },
  { name: "templates list: anonymous", as: "anonymous", method: "GET", path: PT },
  {
    name: "templates create: personal",
    as: "alice",
    method: "POST",
    path: PT,
    body: { title: "Summary", content: "Summarise", icon: "star" },
  },
  {
    name: "templates create: workspace",
    as: "admin",
    method: "POST",
    path: PT,
    body: {
      title: "Team",
      content: "Compare",
      scope: "workspace",
      workspace_id: workspaces.aDefault,
    },
  },
  {
    name: "templates create: workspace needs its id",
    as: "alice",
    method: "POST",
    path: PT,
    body: { title: "T", content: "C", scope: "workspace" },
  },
  {
    name: "templates create: observer refused",
    as: "rita",
    method: "POST",
    path: PT,
    body: { title: "T", content: "C", scope: "workspace", workspace_id: workspaces.aResearch },
  },
  {
    name: "templates create: not a member",
    as: "bob",
    method: "POST",
    path: PT,
    body: { title: "T", content: "C", scope: "workspace", workspace_id: workspaces.aDefault },
  },
  {
    name: "templates create: validation",
    as: "alice",
    method: "POST",
    path: PT,
    body: { title: "x".repeat(201), content: "C", icon: "y".repeat(51), scope: "team" },
  },
  {
    name: "templates update: own",
    as: "alice",
    method: "PATCH",
    path: `${PT}/${extra.template}`,
    body: { title: "Mine, renamed" },
    setup: TEMPLATES,
  },
  {
    name: "templates update: shared by a member",
    as: "admin",
    method: "PATCH",
    path: `${PT}/${extra.workspaceTemplate}`,
    body: { content: "Contrast" },
    setup: TEMPLATES,
  },
  {
    name: "templates update: nothing to update",
    as: "alice",
    method: "PATCH",
    path: `${PT}/${extra.template}`,
    body: { title: null },
    setup: TEMPLATES,
  },
  {
    name: "templates update: someone else's",
    as: "bob",
    method: "PATCH",
    path: `${PT}/${extra.template}`,
    body: { title: "x" },
    setup: TEMPLATES,
  },
  {
    name: "templates update: observer refused",
    as: "rita",
    method: "PATCH",
    path: `${PT}/${extra.researchTemplate}`,
    body: { title: "x" },
    setup: TEMPLATES,
  },
  {
    name: "templates update: missing",
    as: "alice",
    method: "PATCH",
    path: `${PT}/${extra.template}`,
    body: { title: "x" },
  },
  {
    name: "templates delete: own",
    as: "alice",
    method: "DELETE",
    path: `${PT}/${extra.template}`,
    setup: TEMPLATES,
  },
  {
    name: "templates delete: shared by an admin",
    as: "erin",
    method: "DELETE",
    path: `${PT}/${extra.workspaceTemplate}`,
    setup: TEMPLATES,
  },
  {
    name: "templates delete: observer refused",
    as: "rita",
    method: "DELETE",
    path: `${PT}/${extra.researchTemplate}`,
    setup: TEMPLATES,
  },
  {
    name: "templates delete: someone else's",
    as: "bob",
    method: "DELETE",
    path: `${PT}/${extra.template}`,
    setup: TEMPLATES,
  },

  // ── quick access and suggestions ─────────────────────────────────
  { name: "quick access: empty", as: "alice", method: "GET", path: QA },
  {
    name: "quick access: save",
    as: "alice",
    method: "PUT",
    path: QA,
    body: [
      { type: "static", id: "summary" },
      { type: "user", id: extra.template },
      { type: "user", id: extra.workspaceTemplate },
    ],
    setup: TEMPLATES,
    // The old stack's Directus login stamps last_access on the user row these routes update.
    ignoreFields: ["last_access"],
  },
  {
    name: "quick access: read back",
    as: "alice",
    method: "GET",
    path: QA,
    setup: [
      `update directus_users set quick_access_preferences = '[{"type":"static","id":"summary"}]' where email = 'alice.parity@example.com'`,
    ],
  },
  {
    name: "quick access: too many",
    as: "alice",
    method: "PUT",
    path: QA,
    body: [1, 2, 3, 4, 5, 6].map((n) => ({ type: "static", id: `s${n}` })),
  },
  {
    name: "quick access: duplicate",
    as: "alice",
    method: "PUT",
    path: QA,
    body: [
      { type: "static", id: "a" },
      { type: "static", id: "a" },
    ],
  },
  {
    name: "quick access: someone else's template",
    as: "bob",
    method: "PUT",
    path: QA,
    body: [{ type: "user", id: extra.template }],
    setup: TEMPLATES,
  },
  {
    name: "quick access: shared template outside the workspace",
    as: "bob",
    method: "PUT",
    path: QA,
    body: [{ type: "user", id: extra.workspaceTemplate }],
    setup: TEMPLATES,
  },
  {
    name: "quick access: missing template",
    as: "alice",
    method: "PUT",
    path: QA,
    body: [{ type: "user", id: "nope" }],
  },
  {
    name: "quick access: validation",
    as: "alice",
    method: "PUT",
    path: QA,
    body: [{ type: "zz", id: "1" }, 5],
  },
  { name: "quick access: not a list", as: "alice", method: "PUT", path: QA, body: { a: 1 } },
  {
    name: "ai suggestions: hide",
    as: "alice",
    method: "PATCH",
    path: "/api/templates/ai-suggestions",
    body: { hide_ai_suggestions: true },
    // The old stack's Directus login stamps last_access on the user row these routes update.
    ignoreFields: ["last_access"],
  },
  {
    name: "ai suggestions: validation",
    as: "alice",
    method: "PATCH",
    path: "/api/templates/ai-suggestions",
    body: {},
  },
]);
