// Generated by scripts/generate.ts from templates/*.jinja. Do not edit by hand.
/// <reference path="./jinja.d.ts" />
import t0 from "../templates/assign_aspect_centroid.de.jinja" with { type: "text" };
import t1 from "../templates/assign_aspect_centroid.en.jinja" with { type: "text" };
import t2 from "../templates/assign_aspect_centroid.es.jinja" with { type: "text" };
import t3 from "../templates/assign_aspect_centroid.fr.jinja" with { type: "text" };
import t4 from "../templates/assign_aspect_centroid.nl.jinja" with { type: "text" };
import t5 from "../templates/audio_model_system_prompt.en.jinja" with { type: "text" };
import t6 from "../templates/brainstorm.de.jinja" with { type: "text" };
import t7 from "../templates/brainstorm.en.jinja" with { type: "text" };
import t8 from "../templates/brainstorm.es.jinja" with { type: "text" };
import t9 from "../templates/brainstorm.fr.jinja" with { type: "text" };
import t10 from "../templates/brainstorm.nl.jinja" with { type: "text" };
import t11 from "../templates/context_conversations.cs.jinja" with { type: "text" };
import t12 from "../templates/context_conversations.de.jinja" with { type: "text" };
import t13 from "../templates/context_conversations.en.jinja" with { type: "text" };
import t14 from "../templates/context_conversations.es.jinja" with { type: "text" };
import t15 from "../templates/context_conversations.fr.jinja" with { type: "text" };
import t16 from "../templates/context_conversations.it.jinja" with { type: "text" };
import t17 from "../templates/context_conversations.nl.jinja" with { type: "text" };
import t18 from "../templates/context_conversations.uk.jinja" with { type: "text" };
import t19 from "../templates/context_project.en.jinja" with { type: "text" };
import t20 from "../templates/default_whisper_prompt.cs.jinja" with { type: "text" };
import t21 from "../templates/default_whisper_prompt.de.jinja" with { type: "text" };
import t22 from "../templates/default_whisper_prompt.en.jinja" with { type: "text" };
import t23 from "../templates/default_whisper_prompt.es.jinja" with { type: "text" };
import t24 from "../templates/default_whisper_prompt.fr.jinja" with { type: "text" };
import t25 from "../templates/default_whisper_prompt.it.jinja" with { type: "text" };
import t26 from "../templates/default_whisper_prompt.nl.jinja" with { type: "text" };
import t27 from "../templates/default_whisper_prompt.uk.jinja" with { type: "text" };
import t28 from "../templates/generate_artifact.en.jinja" with { type: "text" };
import t29 from "../templates/generate_aspect_image.en.jinja" with { type: "text" };
import t30 from "../templates/generate_aspect_long_summary.de.jinja" with { type: "text" };
import t31 from "../templates/generate_aspect_long_summary.en.jinja" with { type: "text" };
import t32 from "../templates/generate_aspect_long_summary.es.jinja" with { type: "text" };
import t33 from "../templates/generate_aspect_long_summary.fr.jinja" with { type: "text" };
import t34 from "../templates/generate_aspect_long_summary.nl.jinja" with { type: "text" };
import t35 from "../templates/generate_aspect_short_summary.de.jinja" with { type: "text" };
import t36 from "../templates/generate_aspect_short_summary.en.jinja" with { type: "text" };
import t37 from "../templates/generate_aspect_short_summary.es.jinja" with { type: "text" };
import t38 from "../templates/generate_aspect_short_summary.fr.jinja" with { type: "text" };
import t39 from "../templates/generate_aspect_short_summary.nl.jinja" with { type: "text" };
import t40 from "../templates/generate_chat_title.en.jinja" with { type: "text" };
import t41 from "../templates/generate_conversation_summary.cs.jinja" with { type: "text" };
import t42 from "../templates/generate_conversation_summary.de.jinja" with { type: "text" };
import t43 from "../templates/generate_conversation_summary.en.jinja" with { type: "text" };
import t44 from "../templates/generate_conversation_summary.es.jinja" with { type: "text" };
import t45 from "../templates/generate_conversation_summary.fr.jinja" with { type: "text" };
import t46 from "../templates/generate_conversation_summary.it.jinja" with { type: "text" };
import t47 from "../templates/generate_conversation_summary.nl.jinja" with { type: "text" };
import t48 from "../templates/generate_conversation_summary.uk.jinja" with { type: "text" };
import t49 from "../templates/generate_conversation_tag_ids.en.jinja" with { type: "text" };
import t50 from "../templates/generate_conversation_title.en.jinja" with { type: "text" };
import t51 from "../templates/generate_insight_summary.de.jinja" with { type: "text" };
import t52 from "../templates/generate_insight_summary.en.jinja" with { type: "text" };
import t53 from "../templates/generate_insight_summary.es.jinja" with { type: "text" };
import t54 from "../templates/generate_insight_summary.fr.jinja" with { type: "text" };
import t55 from "../templates/generate_insight_summary.nl.jinja" with { type: "text" };
import t56 from "../templates/generate_insight_title.de.jinja" with { type: "text" };
import t57 from "../templates/generate_insight_title.en.jinja" with { type: "text" };
import t58 from "../templates/generate_insight_title.es.jinja" with { type: "text" };
import t59 from "../templates/generate_insight_title.fr.jinja" with { type: "text" };
import t60 from "../templates/generate_insight_title.nl.jinja" with { type: "text" };
import t61 from "../templates/generate_view_extras.de.jinja" with { type: "text" };
import t62 from "../templates/generate_view_extras.en.jinja" with { type: "text" };
import t63 from "../templates/generate_view_extras.es.jinja" with { type: "text" };
import t64 from "../templates/generate_view_extras.fr.jinja" with { type: "text" };
import t65 from "../templates/generate_view_extras.nl.jinja" with { type: "text" };
import t66 from "../templates/get_reply_brainstorm.cs.jinja" with { type: "text" };
import t67 from "../templates/get_reply_brainstorm.de.jinja" with { type: "text" };
import t68 from "../templates/get_reply_brainstorm.en.jinja" with { type: "text" };
import t69 from "../templates/get_reply_brainstorm.es.jinja" with { type: "text" };
import t70 from "../templates/get_reply_brainstorm.fr.jinja" with { type: "text" };
import t71 from "../templates/get_reply_brainstorm.it.jinja" with { type: "text" };
import t72 from "../templates/get_reply_brainstorm.nl.jinja" with { type: "text" };
import t73 from "../templates/get_reply_brainstorm.uk.jinja" with { type: "text" };
import t74 from "../templates/get_reply_summarize.cs.jinja" with { type: "text" };
import t75 from "../templates/get_reply_summarize.de.jinja" with { type: "text" };
import t76 from "../templates/get_reply_summarize.en.jinja" with { type: "text" };
import t77 from "../templates/get_reply_summarize.es.jinja" with { type: "text" };
import t78 from "../templates/get_reply_summarize.fr.jinja" with { type: "text" };
import t79 from "../templates/get_reply_summarize.it.jinja" with { type: "text" };
import t80 from "../templates/get_reply_summarize.nl.jinja" with { type: "text" };
import t81 from "../templates/get_reply_summarize.uk.jinja" with { type: "text" };
import t82 from "../templates/get_reply_system.cs.jinja" with { type: "text" };
import t83 from "../templates/get_reply_system.de.jinja" with { type: "text" };
import t84 from "../templates/get_reply_system.en.jinja" with { type: "text" };
import t85 from "../templates/get_reply_system.es.jinja" with { type: "text" };
import t86 from "../templates/get_reply_system.fr.jinja" with { type: "text" };
import t87 from "../templates/get_reply_system.it.jinja" with { type: "text" };
import t88 from "../templates/get_reply_system.nl.jinja" with { type: "text" };
import t89 from "../templates/get_reply_system.uk.jinja" with { type: "text" };
import t90 from "../templates/initialize_view.de.jinja" with { type: "text" };
import t91 from "../templates/initialize_view.en.jinja" with { type: "text" };
import t92 from "../templates/initialize_view.es.jinja" with { type: "text" };
import t93 from "../templates/initialize_view.fr.jinja" with { type: "text" };
import t94 from "../templates/initialize_view.nl.jinja" with { type: "text" };
import t95 from "../templates/revise_artifact.en.jinja" with { type: "text" };
import t96 from "../templates/suggestions_system.en.jinja" with { type: "text" };
import t97 from "../templates/suggestions_user.en.jinja" with { type: "text" };
import t98 from "../templates/summary.cs.jinja" with { type: "text" };
import t99 from "../templates/summary.de.jinja" with { type: "text" };
import t100 from "../templates/summary.en.jinja" with { type: "text" };
import t101 from "../templates/summary.es.jinja" with { type: "text" };
import t102 from "../templates/summary.fr.jinja" with { type: "text" };
import t103 from "../templates/summary.it.jinja" with { type: "text" };
import t104 from "../templates/summary.nl.jinja" with { type: "text" };
import t105 from "../templates/summary.uk.jinja" with { type: "text" };
import t106 from "../templates/system_chat.cs.jinja" with { type: "text" };
import t107 from "../templates/system_chat.de.jinja" with { type: "text" };
import t108 from "../templates/system_chat.en.jinja" with { type: "text" };
import t109 from "../templates/system_chat.es.jinja" with { type: "text" };
import t110 from "../templates/system_chat.fr.jinja" with { type: "text" };
import t111 from "../templates/system_chat.it.jinja" with { type: "text" };
import t112 from "../templates/system_chat.nl.jinja" with { type: "text" };
import t113 from "../templates/system_chat.uk.jinja" with { type: "text" };
import t114 from "../templates/system_report.cs.jinja" with { type: "text" };
import t115 from "../templates/system_report.de.jinja" with { type: "text" };
import t116 from "../templates/system_report.en.jinja" with { type: "text" };
import t117 from "../templates/system_report.es.jinja" with { type: "text" };
import t118 from "../templates/system_report.fr.jinja" with { type: "text" };
import t119 from "../templates/system_report.it.jinja" with { type: "text" };
import t120 from "../templates/system_report.nl.jinja" with { type: "text" };
import t121 from "../templates/system_report.uk.jinja" with { type: "text" };
import t122 from "../templates/text_structuring_model_message.en.jinja" with { type: "text" };
import t123 from "../templates/text_structuring_model_system_prompt.en.jinja" with { type: "text" };
import t124 from "../templates/transcript_correction_workflow.en.jinja" with { type: "text" };
import t125 from "../templates/transcript_from_audio_workflow.en.jinja" with { type: "text" };
import t126 from "../templates/translate_transcription.cs.jinja" with { type: "text" };
import t127 from "../templates/translate_transcription.de.jinja" with { type: "text" };
import t128 from "../templates/translate_transcription.en.jinja" with { type: "text" };
import t129 from "../templates/translate_transcription.es.jinja" with { type: "text" };
import t130 from "../templates/translate_transcription.fr.jinja" with { type: "text" };
import t131 from "../templates/translate_transcription.it.jinja" with { type: "text" };
import t132 from "../templates/translate_transcription.nl.jinja" with { type: "text" };
import t133 from "../templates/translate_transcription.uk.jinja" with { type: "text" };

export const TEMPLATES: Readonly<Record<string, string>> = {
  "assign_aspect_centroid.de.jinja": t0,
  "assign_aspect_centroid.en.jinja": t1,
  "assign_aspect_centroid.es.jinja": t2,
  "assign_aspect_centroid.fr.jinja": t3,
  "assign_aspect_centroid.nl.jinja": t4,
  "audio_model_system_prompt.en.jinja": t5,
  "brainstorm.de.jinja": t6,
  "brainstorm.en.jinja": t7,
  "brainstorm.es.jinja": t8,
  "brainstorm.fr.jinja": t9,
  "brainstorm.nl.jinja": t10,
  "context_conversations.cs.jinja": t11,
  "context_conversations.de.jinja": t12,
  "context_conversations.en.jinja": t13,
  "context_conversations.es.jinja": t14,
  "context_conversations.fr.jinja": t15,
  "context_conversations.it.jinja": t16,
  "context_conversations.nl.jinja": t17,
  "context_conversations.uk.jinja": t18,
  "context_project.en.jinja": t19,
  "default_whisper_prompt.cs.jinja": t20,
  "default_whisper_prompt.de.jinja": t21,
  "default_whisper_prompt.en.jinja": t22,
  "default_whisper_prompt.es.jinja": t23,
  "default_whisper_prompt.fr.jinja": t24,
  "default_whisper_prompt.it.jinja": t25,
  "default_whisper_prompt.nl.jinja": t26,
  "default_whisper_prompt.uk.jinja": t27,
  "generate_artifact.en.jinja": t28,
  "generate_aspect_image.en.jinja": t29,
  "generate_aspect_long_summary.de.jinja": t30,
  "generate_aspect_long_summary.en.jinja": t31,
  "generate_aspect_long_summary.es.jinja": t32,
  "generate_aspect_long_summary.fr.jinja": t33,
  "generate_aspect_long_summary.nl.jinja": t34,
  "generate_aspect_short_summary.de.jinja": t35,
  "generate_aspect_short_summary.en.jinja": t36,
  "generate_aspect_short_summary.es.jinja": t37,
  "generate_aspect_short_summary.fr.jinja": t38,
  "generate_aspect_short_summary.nl.jinja": t39,
  "generate_chat_title.en.jinja": t40,
  "generate_conversation_summary.cs.jinja": t41,
  "generate_conversation_summary.de.jinja": t42,
  "generate_conversation_summary.en.jinja": t43,
  "generate_conversation_summary.es.jinja": t44,
  "generate_conversation_summary.fr.jinja": t45,
  "generate_conversation_summary.it.jinja": t46,
  "generate_conversation_summary.nl.jinja": t47,
  "generate_conversation_summary.uk.jinja": t48,
  "generate_conversation_tag_ids.en.jinja": t49,
  "generate_conversation_title.en.jinja": t50,
  "generate_insight_summary.de.jinja": t51,
  "generate_insight_summary.en.jinja": t52,
  "generate_insight_summary.es.jinja": t53,
  "generate_insight_summary.fr.jinja": t54,
  "generate_insight_summary.nl.jinja": t55,
  "generate_insight_title.de.jinja": t56,
  "generate_insight_title.en.jinja": t57,
  "generate_insight_title.es.jinja": t58,
  "generate_insight_title.fr.jinja": t59,
  "generate_insight_title.nl.jinja": t60,
  "generate_view_extras.de.jinja": t61,
  "generate_view_extras.en.jinja": t62,
  "generate_view_extras.es.jinja": t63,
  "generate_view_extras.fr.jinja": t64,
  "generate_view_extras.nl.jinja": t65,
  "get_reply_brainstorm.cs.jinja": t66,
  "get_reply_brainstorm.de.jinja": t67,
  "get_reply_brainstorm.en.jinja": t68,
  "get_reply_brainstorm.es.jinja": t69,
  "get_reply_brainstorm.fr.jinja": t70,
  "get_reply_brainstorm.it.jinja": t71,
  "get_reply_brainstorm.nl.jinja": t72,
  "get_reply_brainstorm.uk.jinja": t73,
  "get_reply_summarize.cs.jinja": t74,
  "get_reply_summarize.de.jinja": t75,
  "get_reply_summarize.en.jinja": t76,
  "get_reply_summarize.es.jinja": t77,
  "get_reply_summarize.fr.jinja": t78,
  "get_reply_summarize.it.jinja": t79,
  "get_reply_summarize.nl.jinja": t80,
  "get_reply_summarize.uk.jinja": t81,
  "get_reply_system.cs.jinja": t82,
  "get_reply_system.de.jinja": t83,
  "get_reply_system.en.jinja": t84,
  "get_reply_system.es.jinja": t85,
  "get_reply_system.fr.jinja": t86,
  "get_reply_system.it.jinja": t87,
  "get_reply_system.nl.jinja": t88,
  "get_reply_system.uk.jinja": t89,
  "initialize_view.de.jinja": t90,
  "initialize_view.en.jinja": t91,
  "initialize_view.es.jinja": t92,
  "initialize_view.fr.jinja": t93,
  "initialize_view.nl.jinja": t94,
  "revise_artifact.en.jinja": t95,
  "suggestions_system.en.jinja": t96,
  "suggestions_user.en.jinja": t97,
  "summary.cs.jinja": t98,
  "summary.de.jinja": t99,
  "summary.en.jinja": t100,
  "summary.es.jinja": t101,
  "summary.fr.jinja": t102,
  "summary.it.jinja": t103,
  "summary.nl.jinja": t104,
  "summary.uk.jinja": t105,
  "system_chat.cs.jinja": t106,
  "system_chat.de.jinja": t107,
  "system_chat.en.jinja": t108,
  "system_chat.es.jinja": t109,
  "system_chat.fr.jinja": t110,
  "system_chat.it.jinja": t111,
  "system_chat.nl.jinja": t112,
  "system_chat.uk.jinja": t113,
  "system_report.cs.jinja": t114,
  "system_report.de.jinja": t115,
  "system_report.en.jinja": t116,
  "system_report.es.jinja": t117,
  "system_report.fr.jinja": t118,
  "system_report.it.jinja": t119,
  "system_report.nl.jinja": t120,
  "system_report.uk.jinja": t121,
  "text_structuring_model_message.en.jinja": t122,
  "text_structuring_model_system_prompt.en.jinja": t123,
  "transcript_correction_workflow.en.jinja": t124,
  "transcript_from_audio_workflow.en.jinja": t125,
  "translate_transcription.cs.jinja": t126,
  "translate_transcription.de.jinja": t127,
  "translate_transcription.en.jinja": t128,
  "translate_transcription.es.jinja": t129,
  "translate_transcription.fr.jinja": t130,
  "translate_transcription.it.jinja": t131,
  "translate_transcription.nl.jinja": t132,
  "translate_transcription.uk.jinja": t133,
};
