# Accepted audio/video file formats for processing
accepted_formats:
  - mp3
  - wav
  - m4a
  #- mp4

# Output paths for the resulting CSV files (or any other destination you choose)
conversation_output_path: "server/dembrane/audio_lightrag/data/directus_etl_data/conversation.csv"
project_output_path: "server/dembrane/audio_lightrag/data/directus_etl_data/project.csv"

project_request:
  query:
    fields:
      - id
      - name
      - language
      - context
      - default_conversation_title
      - default_conversation_description
    limit: 100000

conversation_request:
  query:
    fields:
      - id
      - project_id
      - chunks.id
      - chunks.path
      - chunks.timestamp
    limit: 100000
    deep:
      chunks:
        _limit: 100000
        _sort: timestamp