name: PR - Build images | Merge - Publish images

on:
  # Run on PRs (to check if the images can be built)
  pull_request:
    branches:
      - main
  # Run on pushes to main (to publish the images)
  push:
    branches:
      - main

jobs:
  ci-servers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          # Directus
          - name: dbr-echo-directus
            context: ./echo/directus
            dockerfile: Dockerfile
            tag: dbr-echo-directus
            build_args: ""

          # Shared image for server and worker
          - name: dbr-echo-server
            context: ./echo/server
            dockerfile: Dockerfile
            tag: dbr-echo-server
            build_args: ""

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        # Login step runs on both PR and push events
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Build (also push sometimes) ${{ matrix.image.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.context }}/${{ matrix.image.dockerfile }}
          # Only push if the event is a push event to main.
          push: ${{ github.event_name == 'push' }}
          tags: registry.digitalocean.com/dbr-cr/${{ matrix.image.tag }}:${{ github.sha }}
          build-args: ${{ matrix.image.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
