name: build and push images ;)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          # directus
          - name: dbr-echo-drectus
            context: ./echo/directus
            dockerfile: Dockerfile
            tag: dbr-echo-directus
            build_args: ""

          # shared image for server and worker
          - name: dbr-echo-server
            context: ./echo/server
            dockerfile: Dockerfile
            tag: dbr-echo-server
            build_args: ""

          # shared image for admin dashboard and portal
          - name: dbr-echo-client-web
            context: ./echo/frontend
            dockerfile: Dockerfile
            tag: dbr-echo-client-web
            build_args: ""

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Build and Push ${{ matrix.image.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.context }}/${{ matrix.image.dockerfile }}
          push: true
          tags: registry.digitalocean.com/dbr-cr/${{ matrix.image.tag }}:${{ github.sha }}
          build-args: ${{ matrix.image.build_args }}
