name: Deploy Portal Staging
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PORTAL }}
on:
  push:
    branches:
      - main

jobs:
  deploy-portal-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 10
          run_install: true
          cwd: echo/frontend

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
        working-directory: echo/frontend

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=staging --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: echo/frontend

      - name: Build Project Artifacts
        run: vercel build --target=staging --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: echo/frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --target=staging --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: echo/frontend